-- ============================================================================
-- ORBITAL 360 — Migration 07c · SEED Criterios 4-5 (EN/AR) — re-ejecutable
-- C4 · Partners & Suppliers — C5 · Customers
-- ============================================================================
insert into public.assessment_questions
  (code, criterion_code, ref, sort, block_en, block_ar, question_en, question_ar,
   context_en, context_ar, evidence_en, evidence_ar, levels_en, levels_ar)
values
('P 4.1','c4','4.1',1,'Segmentation','التقسيم',
 'Segmentation of partners and suppliers','تقسيم الشركاء والموردين',
 'Not all partners contribute the same. Segmenting them focuses management effort where it generates the most strategic value for the organisation.',
 'لا يسهم جميع الشركاء بالقدر نفسه؛ فتقسيمهم يوجه جهد الإدارة حيث يولّد أكبر قيمة استراتيجية للمؤسسة.',
 E'• Segmented map of partners and suppliers\n• Documented segmentation criteria (strategic, tactical, operational)\n• Differentiated relationship plan per segment\n• Minutes of annual segmentation reviews\n• Strategic decisions that used the segmentation',
 E'• خريطة مقسمة للشركاء والموردين\n• معايير تقسيم موثقة (استراتيجي، تكتيكي، تشغيلي)\n• خطة علاقات متمايزة لكل شريحة\n• محاضر مراجعة سنوية للتقسيم\n• قرارات استراتيجية استخدمت التقسيم',
 '["No evidence of partner and supplier segmentation","Partner and supplier segmentation exists","Segmentation based on purpose, vision and strategy for at least 40% of partners and suppliers, reviewed in the last strategic cycle","Segmentation based on purpose, vision and strategy for at least 60% of partners and suppliers","Segmentation based on purpose, vision and strategy for at least 80% of partners and suppliers, reviewed in the last strategic cycle","Segmentation covers 100% of partners and suppliers, is reviewed annually and actively used for strategic decision-making"]'::jsonb,
 '["لا يوجد دليل على تقسيم الشركاء والموردين","يوجد تقسيم للشركاء والموردين","تقسيم مبني على الغاية والرؤية والاستراتيجية لـ 40% على الأقل من الشركاء والموردين، رُوجع في آخر دورة استراتيجية","تقسيم مبني على الغاية والرؤية والاستراتيجية لـ 60% على الأقل من الشركاء والموردين","تقسيم مبني على الغاية والرؤية والاستراتيجية لـ 80% على الأقل رُوجع في آخر دورة استراتيجية","تقسيم يغطي 100% من الشركاء والموردين يُراجع سنوياً ويُستخدم فعلياً في القرار الاستراتيجي"]'::jsonb),

('P 4.2','c4','4.2',2,'Trust and shared value','الثقة والقيمة المشتركة',
 'Relationship of trust and shared value','علاقة ثقة وقيمة مشتركة',
 'The best alliances work when both sides win. Measuring shared value prevents unbalanced relationships that silently erode over time.',
 'أفضل التحالفات تلك التي يربح فيها الطرفان؛ وقياس القيمة المشتركة يمنع العلاقات غير المتوازنة التي تتآكل بصمت مع الزمن.',
 E'• Perception surveys of partners and suppliers\n• Joint projects documented with results\n• Shared-value agreements (joint business plans)\n• Mutual-value indicators (savings, shared revenue)\n• Jointly published success stories',
 E'• استطلاعات إدراك للشركاء والموردين\n• مشاريع مشتركة موثقة بنتائجها\n• اتفاقيات قيمة مشتركة (خطط أعمال مشتركة)\n• مؤشرات قيمة متبادلة (وفورات، إيرادات مشتركة)\n• قصص نجاح منشورة بالاشتراك',
 '["No measurements of shared-value generation","The organisation measures the perception of shared value with its partners and suppliers","Shared value positively perceived by 40%","Shared value positively perceived by 60%","Shared value positively perceived by 80%","Shared value positively perceived by 100% of partners and suppliers, with measurable results in joint projects"]'::jsonb,
 '["لا توجد قياسات لتوليد القيمة المشتركة","تقيس المؤسسة إدراك القيمة المشتركة مع شركائها ومورديها","قيمة مشتركة يدركها إيجابياً 40%","قيمة مشتركة يدركها إيجابياً 60%","قيمة مشتركة يدركها إيجابياً 80%","قيمة مشتركة يدركها إيجابياً 100% من الشركاء والموردين بنتائج قابلة للقياس في المشاريع المشتركة"]'::jsonb),

('P 4.3','c4','4.3',3,'Trust and shared value','الثقة والقيمة المشتركة',
 'Relationships sustained over time','علاقات مستدامة عبر الزمن',
 'Long partner relationships cut costs and enable more ambitious projects. Longevity signals the health of the alliance and mutual trust.',
 'العلاقات الطويلة مع الشركاء تخفض التكاليف وتتيح مشاريع أكثر طموحاً؛ وطول العلاقة مؤشر على صحة التحالف والثقة المتبادلة.',
 E'• History of partner relationship longevity\n• Long-term contract renewals\n• Partner satisfaction surveys\n• Awards or mentions for sustainable alliances\n• Cases jointly published with partners',
 E'• سجل مدة العلاقات مع الشركاء\n• تجديد عقود طويلة الأجل\n• استطلاعات رضا الشركاء\n• جوائز أو إشادات بالتحالفات المستدامة\n• حالات منشورة بالاشتراك مع الشركاء',
 '["No evidence of relationship systems supporting sustainability with partners","Relationships of at least 3 years with at least 50% of partners","3+ year relationships with 50% of partners, positively perceived in at least 40% of cases","3+ year relationships with 50% of partners, positively perceived in at least 60% of cases","3+ year relationships with 50% of partners, positively perceived in at least 80% of cases","Relationships over 5 years with most key partners, positively perceived in 100% of cases, externally recognised as an example of sustainable alliance"]'::jsonb,
 '["لا يوجد دليل على أنظمة علاقات تدعم الاستدامة مع الشركاء","علاقات لا تقل عن 3 سنوات مع 50% على الأقل من الشركاء","علاقات 3 سنوات فأكثر مع 50% من الشركاء يُدركها إيجابياً 40% على الأقل من الحالات","علاقات 3 سنوات فأكثر مع 50% من الشركاء يُدركها إيجابياً 60% على الأقل من الحالات","علاقات 3 سنوات فأكثر مع 50% من الشركاء يُدركها إيجابياً 80% على الأقل من الحالات","علاقات تتجاوز 5 سنوات مع معظم الشركاء الرئيسيين يُدركها إيجابياً 100% من الحالات ومعترف بها خارجياً كمثال للتحالف المستدام"]'::jsonb),

('P 4.4','c4','4.4',4,'Trust and shared value','الثقة والقيمة المشتركة',
 'Trust with partners/suppliers, short and long term','الثقة مع الشركاء/الموردين قصير وطويل المدى',
 'Trust is the foundation of any alliance. Without measuring it you cannot tell whether it is being built or silently destroyed over time.',
 'الثقة أساس أي تحالف؛ وبدون قياسها لا يُعرف ما إذا كانت تُبنى أم تُهدم بصمت مع الوقت.',
 E'• Annual partner trust surveys\n• Supplier Net Promoter Score (NPS) indicators\n• Post-survey action plans with follow-up\n• Joint monitoring committees\n• Long-term confidentiality and collaboration agreements',
 E'• استطلاعات ثقة سنوية للشركاء\n• مؤشرات NPS للموردين\n• خطط عمل بعد الاستطلاعات مع متابعة\n• لجان متابعة مشتركة\n• اتفاقيات سرية وتعاون طويلة الأجل',
 '["No plan to measure the degree of trust with partners and suppliers","Measurements exist showing trust between the organisation and partners/suppliers","Trust measurements for 40%, short and long term","Trust measurements for 60%, short and long term","Trust measurements for 80%, short and long term","Trust measurements for 100%, short and long term, with specific action plans to maintain and develop it"]'::jsonb,
 '["لا توجد خطة لقياس درجة الثقة مع الشركاء والموردين","توجد قياسات تُظهر الثقة بين المؤسسة والشركاء/الموردين","قياسات ثقة لـ 40% على المديين القصير والطويل","قياسات ثقة لـ 60% على المديين القصير والطويل","قياسات ثقة لـ 80% على المديين القصير والطويل","قياسات ثقة لـ 100% على المديين القصير والطويل مع خطط عمل محددة لصونها وتنميتها"]'::jsonb),

('P 4.5','c4','4.5',5,'Sustainability','الاستدامة',
 'Commitment to the circular economy','الالتزام بالاقتصاد الدائري',
 'Advancing towards the circular economy is a shared responsibility with the value chain, cutting environmental impact and operating costs sustainably.',
 'التقدم نحو الاقتصاد الدائري مسؤولية مشتركة مع سلسلة القيمة تخفض الأثر البيئي والتكاليف التشغيلية بشكل مستدام.',
 E'• Organisation''s circular-economy plan\n• Supplier selection criteria including circularity\n• Circularity audits of suppliers\n• Indicators (% recycled material, avoided waste)\n• Sustainability report with published data',
 E'• خطة اقتصاد دائري للمؤسسة\n• معايير اختيار موردين تشمل الدائرية\n• تدقيقات دائرية للموردين\n• مؤشرات (% مواد معاد تدويرها، نفايات مُتجنَّبة)\n• تقرير استدامة ببيانات منشورة',
 '["No management plan for advancing towards the circular economy","Measurements showing recognition of the commitment and achievements towards the circular economy among partners and suppliers","Recognition of commitment and achievements towards the circular economy among 40% of partners and suppliers","Recognition and achievements among 60% of partners and suppliers","Recognition and achievements among 80% of partners and suppliers","Circular-economy commitment recognised by 100% of key partners and suppliers, with systematically measured indicators and results published in the sustainability report"]'::jsonb,
 '["لا توجد خطة إدارة للتقدم نحو الاقتصاد الدائري","قياسات تُظهر الاعتراف بالالتزام والإنجازات نحو الاقتصاد الدائري لدى الشركاء والموردين","اعتراف بالالتزام والإنجازات نحو الاقتصاد الدائري لدى 40% من الشركاء والموردين","اعتراف وإنجازات لدى 60% من الشركاء والموردين","اعتراف وإنجازات لدى 80% من الشركاء والموردين","التزام بالاقتصاد الدائري معترف به لدى 100% من الشركاء والموردين الرئيسيين بمؤشرات تُقاس منهجياً ونتائج منشورة في تقرير الاستدامة"]'::jsonb),

('P 4.6','c4','4.6',6,'Shared culture','ثقافة مشتركة',
 'Customer-oriented culture through partners/suppliers','ثقافة موجهة للعميل عبر الشركاء/الموردين',
 'Partners and suppliers impact the end customer''s experience. Aligning them with the customer culture protects the organisation''s value proposition.',
 'يؤثر الشركاء والموردون في تجربة العميل النهائي؛ ومواءمتهم مع ثقافة العميل تحمي عرض القيمة الذي صممته المؤسسة.',
 E'• Partner-customer management procedure\n• Customer surveys on the experience with partners\n• Tripartite service-level agreements (SLAs)\n• Jointly reviewed partner-customer plans\n• End-customer satisfaction indicators with partners',
 E'• إجراء إدارة العلاقة شريك-عميل\n• استطلاعات عملاء حول التجربة مع الشركاء\n• اتفاقيات مستوى خدمة ثلاثية\n• خطط شريك-عميل تُراجع بالاشتراك\n• مؤشرات رضا العميل النهائي مع الشركاء',
 '["No system supporting relationship management aligned with the purpose and strategy between partners and customers","Systems exist supporting relationship management aligned with the purpose and strategy between partners and customers","Systems positively perceived by 40% of customers","Systems positively perceived by 60% of customers","Systems positively perceived by 80% of customers","Systems positively perceived by 100% of customers, with joint partner-customer plans reviewed periodically"]'::jsonb,
 '["لا يوجد نظام يدعم إدارة علاقات متسقة مع الغاية والاستراتيجية بين الشركاء والعملاء","توجد أنظمة تدعم إدارة علاقات متسقة مع الغاية والاستراتيجية بين الشركاء والعملاء","أنظمة يدركها إيجابياً 40% من العملاء","أنظمة يدركها إيجابياً 60% من العملاء","أنظمة يدركها إيجابياً 80% من العملاء","أنظمة يدركها إيجابياً 100% من العملاء مع خطط شريك-عميل مشتركة تُراجع دورياً"]'::jsonb),

('P 4.7','c4','4.7',7,'Mutual benefit','المنفعة المتبادلة',
 'Proactive work for mutual benefit','عمل استباقي للمنفعة المتبادلة',
 'When partner and organisation share objectives and achieve them together, resilient alliances and replicable, externally recognisable success stories emerge.',
 'عندما يتشارك الشريك والمؤسسة الأهداف ويحققانها معاً، تنشأ تحالفات مرنة وقصص نجاح قابلة للتكرار ومعترف بها خارجياً.',
 E'• Formalised shared goals with partners\n• Mutual-benefit KPIs (shared savings, shared revenue)\n• Periodic shared-objective review sessions\n• Success stories with quantified results\n• Joint improvement plans with owners',
 E'• أهداف مشتركة رسمية مع الشركاء\n• مؤشرات منفعة متبادلة (وفورات وإيرادات مشتركة)\n• جلسات مراجعة دورية للأهداف المشتركة\n• قصص نجاح بنتائج مُكمّاة\n• خطط تحسين مشتركة مع مسؤولين',
 '["No evidence that the organisation sets objectives with partners/suppliers to achieve mutual benefit","Working models exist that set objectives with partners/suppliers to achieve mutual benefit","Models for 40% of partners/suppliers aligned with purpose, vision and strategy","Models for 40% of partners/suppliers, achieved in 50% of cases","Models for 60% of partners/suppliers, achieved in 75% of cases","Models for 80% of partners/suppliers, achieved in more than 85% of cases, with systematic review and joint improvement plans"]'::jsonb,
 '["لا يوجد دليل على أن المؤسسة تضع أهدافاً مع الشركاء/الموردين لتحقيق منفعة متبادلة","توجد نماذج عمل تضع أهدافاً مع الشركاء/الموردين لتحقيق منفعة متبادلة","نماذج لـ 40% من الشركاء/الموردين متسقة مع الغاية والرؤية والاستراتيجية","نماذج لـ 40% من الشركاء/الموردين تتحقق في 50% من الحالات","نماذج لـ 60% من الشركاء/الموردين تتحقق في 75% من الحالات","نماذج لـ 80% من الشركاء/الموردين تتحقق في أكثر من 85% من الحالات بمراجعة منهجية وخطط تحسين مشتركة"]'::jsonb),

('P 4.8','c4','4.8',8,'Recognition','التقدير',
 'Recognition management for partners and suppliers','إدارة تقدير الشركاء والموردين',
 'Recognising partners strengthens the bond, turns them into ambassadors and attracts new strategic alliances to the organisation''s future ecosystem.',
 'تقدير الشركاء يقوي الرابطة ويحولهم إلى سفراء ويجذب تحالفات استراتيجية جديدة إلى منظومة المؤسسة مستقبلاً.',
 E'• Partner recognition programme (Partner of the Year)\n• Recognition perception surveys\n• Annual recognition events\n• Public communication of good practices\n• Partner loyalty and churn indicators',
 E'• برنامج تقدير الشركاء (شريك العام)\n• استطلاعات إدراك التقدير\n• فعاليات تقدير سنوية\n• نشر عام للممارسات الجيدة\n• مؤشرات ولاء الشركاء ودورانهم',
 '["No defined plan to recognise partners'' work and/or motivate them","A defined plan exists to recognise partners'' work and/or motivate them","Recognition positively perceived by 40%","Recognition positively perceived by 60%","Recognition positively perceived by more than 80%","Recognition positively perceived by 100% of partners, with public recognition events and external communication of good practices"]'::jsonb,
 '["لا توجد خطة محددة لتقدير عمل الشركاء و/أو تحفيزهم","توجد خطة محددة لتقدير عمل الشركاء و/أو تحفيزهم","تقدير يدركه إيجابياً 40%","تقدير يدركه إيجابياً 60%","تقدير يدركه إيجابياً أكثر من 80%","تقدير يدركه إيجابياً 100% من الشركاء مع فعاليات تقدير عامة ونشر خارجي للممارسات الجيدة"]'::jsonb),

('P 4.9','c4','4.9',9,'Collaboration','التعاون',
 'Collaboration in learning networks','التعاون في شبكات التعلم',
 'Collaborating in networks amplifies learning, speeds up innovation and multiplies impact beyond each organisation''s individual capabilities.',
 'التعاون في الشبكات يضاعف التعلم ويسرّع الابتكار ويضخم الأثر بما يتجاوز قدرات كل مؤسسة منفردة.',
 E'• Collaborative projects documented with results\n• Membership of associations or sector clusters\n• Participation in European or joint R&D projects\n• Joint publications with partners\n• External recognition of the collaborative culture',
 E'• مشاريع تعاونية موثقة بنتائجها\n• عضوية جمعيات أو تجمعات قطاعية\n• مشاركة في مشاريع أوروبية أو بحث وتطوير مشتركة\n• منشورات مشتركة مع الشركاء\n• اعتراف خارجي بثقافة التعاون',
 '["No collaborative projects evidencing knowledge sharing, learning and feedback between the organisation and its partners","Collaborative projects exist ensuring knowledge sharing, learning and feedback","Collaborative projects achieving 40% of results","Collaborative projects achieving 60% of results","Collaborative projects achieving more than 80% of results","The organisation leads or actively belongs to sector networks/associations with partners, with publishable results and external recognition of its collaborative culture"]'::jsonb,
 '["لا توجد مشاريع تعاونية تُثبت تبادل المعرفة والتعلم والتغذية الراجعة بين المؤسسة وشركائها","توجد مشاريع تعاونية تضمن تبادل المعرفة والتعلم والتغذية الراجعة","مشاريع تعاونية تحقق 40% من النتائج","مشاريع تعاونية تحقق 60% من النتائج","مشاريع تعاونية تحقق أكثر من 80% من النتائج","تقود المؤسسة أو تنتمي بنشاط إلى شبكات/جمعيات قطاعية مع الشركاء بنتائج قابلة للنشر واعتراف خارجي بثقافتها التعاونية"]'::jsonb),

('P 4.10','c4','4.10',10,'Improvement','التحسين',
 'Improving the value proposition to partners','تحسين عرض القيمة للشركاء',
 'If you do not measure how partners perceive the value they receive, the proposition erodes without the organisation noticing in time.',
 'إن لم يُقس كيف يدرك الشركاء القيمة التي يتلقونها، يتآكل العرض دون أن تلحظ المؤسسة ذلك في الوقت المناسب.',
 E'• Scorecard with partner indicators\n• Documented improvement plans per partner\n• Annual review sessions with key partners\n• Partner satisfaction surveys with improvement results\n• Indicators of the evolution of jointly generated value',
 E'• لوحة مؤشرات للشركاء\n• خطط تحسين موثقة لكل شريك\n• جلسات مراجعة سنوية مع الشركاء الرئيسيين\n• استطلاعات رضا الشركاء بنتائج التحسين\n• مؤشرات تطور القيمة المولدة معاً',
 '["No indicators to detect opportunities to improve the partner value proposition","Indicators sporadically detect opportunities to improve the value proposition","Indicators and improvement plans for at least 40% of partners","Indicators and improvement plans for at least 60% of partners","Indicators and improvement plans for at least 80% of partners","Indicators and improvement plans for 100% of key partners, with annual review and measurable results in satisfaction and generated value"]'::jsonb,
 '["لا توجد مؤشرات لرصد فرص تحسين عرض القيمة للشركاء","مؤشرات ترصد فرص التحسين بشكل متفرق","مؤشرات وخطط تحسين لـ 40% على الأقل من الشركاء","مؤشرات وخطط تحسين لـ 60% على الأقل من الشركاء","مؤشرات وخطط تحسين لـ 80% على الأقل من الشركاء","مؤشرات وخطط تحسين لـ 100% من الشركاء الرئيسيين بمراجعة سنوية ونتائج قابلة للقياس في الرضا والقيمة المولدة"]'::jsonb),

-- ============================ C5 · CUSTOMERS ============================
('P 5.1','c5','5.1',1,'Segmentation','التقسيم',
 'Identifying customer types (segmentation)','تحديد أنواع العملاء (التقسيم)',
 'Each customer segment has different needs. Segmenting lets you offer suitable, efficient value propositions to each without wasting resources.',
 'لكل شريحة عملاء احتياجات مختلفة؛ والتقسيم يتيح تقديم عروض قيمة ملائمة وفعالة لكل شريحة دون هدر الموارد.',
 E'• CRM with operational segmentation\n• Formal segmentation criteria document\n• Perception surveys per segment\n• Marketing and service actions differentiated by segment\n• Sales and satisfaction results per segment',
 E'• CRM بتقسيم تشغيلي\n• وثيقة رسمية بمعايير التقسيم\n• استطلاعات إدراك لكل شريحة\n• إجراءات تسويق وخدمة متمايزة حسب الشريحة\n• نتائج مبيعات ورضا حسب الشريحة',
 '["No evidence of customer segmentation or identification of their needs","Current and potential customers are identified and segmented by their needs, to establish customer-oriented actions","Segmentation positively perceived by 40% of customers","Segmentation positively perceived by 60% of customers","Segmentation positively perceived by 80% of customers","Segmentation positively perceived by 100% of customers, with annual review and per-segment actions generating measurable results"]'::jsonb,
 '["لا يوجد دليل على تقسيم العملاء أو تحديد احتياجاتهم","يُحدَّد العملاء الحاليون والمحتملون ويقسَّمون حسب احتياجاتهم لوضع إجراءات موجهة للعميل","تقسيم يدركه إيجابياً 40% من العملاء","تقسيم يدركه إيجابياً 60% من العملاء","تقسيم يدركه إيجابياً 80% من العملاء","تقسيم يدركه إيجابياً 100% من العملاء بمراجعة سنوية وإجراءات لكل شريحة تولد نتائج قابلة للقياس"]'::jsonb),

('P 5.2','c5','5.2',2,'Customer experience','تجربة العميل',
 'Value proposition and customer experience','عرض القيمة وتجربة العميل',
 'Customer experience drives loyalty and recommendation. If it is not measured, the organisation manages its most important, critical relationship blindly.',
 'تجربة العميل تحدد الولاء والتوصية؛ وإن لم تُقس، تدير المؤسسة أهم علاقاتها وأكثرها حساسية على غير هدى.',
 E'• Customer journey map per segment\n• NPS, CSAT, CES indicators\n• Voice of the Customer (VoC) programme\n• Documented touchpoints pre-sale, sale and after-sale\n• Improvement plans based on experience data',
 E'• خريطة رحلة العميل لكل شريحة\n• مؤشرات NPS وCSAT وCES\n• برنامج صوت العميل (VoC)\n• نقاط تماس موثقة قبل البيع وأثناءه وبعده\n• خطط تحسين مبنية على بيانات التجربة',
 '["No evidence that the customer experience is identified","Evidence that the organisation knows the experience before, during and after acquiring the product/service, but it has not been measured","Experience measurements for 40% of customers","Experience measurements for 60% of customers","Experience measurements for 80% of customers","Experience measurements for 100% of customers, with continuous-improvement plans based on results (NPS, CSAT or other sector benchmark indicators)"]'::jsonb,
 '["لا يوجد دليل على تحديد تجربة العميل","دلائل على أن المؤسسة تعرف التجربة قبل اقتناء المنتج/الخدمة وأثناءه وبعده لكنها لم تُقس","قياسات تجربة لـ 40% من العملاء","قياسات تجربة لـ 60% من العملاء","قياسات تجربة لـ 80% من العملاء","قياسات تجربة لـ 100% من العملاء مع خطط تحسين مستمر مبنية على النتائج (NPS أو CSAT أو مؤشرات مرجعية قطاعية أخرى)"]'::jsonb),

('P 5.3','c5','5.3',3,'Customer experience','تجربة العميل',
 'Managing customer needs','إدارة احتياجات العملاء',
 'Knowing customer needs at every stage avoids surprises and lets you anticipate solutions before the customer explicitly asks for them.',
 'معرفة احتياجات العميل في كل مرحلة تجنب المفاجآت وتتيح استباق الحلول قبل أن يطلبها العميل صراحة.',
 E'• CRM system with interaction history\n• Complaints and requests management procedure\n• Response and resolution time indicators\n• Documented personalisation cases\n• Traceability of actions per customer',
 E'• نظام CRM بسجل التفاعلات\n• إجراء إدارة الشكاوى والطلبات\n• مؤشرات زمن الاستجابة والحل\n• حالات تخصيص موثقة\n• تتبع الإجراءات لكل عميل',
 '["No evidence of a relationship with customers at every value-creation stage","Measurements identifying the relationship with customers at every stage of the value chain","Measurements, acting on needs for 40% of customers","Measurements, acting on needs for 60% of customers","Measurements, acting on needs for 80% of customers","Measurements, acting on the needs of 100% of customers, with personalised responses and traceability of actions"]'::jsonb,
 '["لا يوجد دليل على علاقة مع العملاء في كل مراحل خلق القيمة","قياسات تحدد العلاقة مع العملاء في كل مراحل سلسلة القيمة","قياسات والعمل وفق الاحتياجات لـ 40% من العملاء","قياسات والعمل وفق الاحتياجات لـ 60% من العملاء","قياسات والعمل وفق الاحتياجات لـ 80% من العملاء","قياسات والعمل وفق احتياجات 100% من العملاء باستجابات مخصصة وتتبع للإجراءات"]'::jsonb),

('P 5.4','c5','5.4',4,'Behaviour','السلوك',
 'Knowledge of customer behaviour','معرفة سلوك العملاء',
 'Understanding why customers buy, leave or repeat lets you anticipate trends and design better experiences at every touchpoint of the customer journey.',
 'فهم لماذا يشتري العملاء أو يغادرون أو يكررون يتيح استباق الاتجاهات وتصميم تجارب أفضل في كل نقطة تماس من رحلة العميل.',
 E'• Behaviour analytics (web, app, point of sale)\n• Market and consumer behaviour studies\n• Predictive churn or purchase models\n• Dynamic offer personalisation\n• Cases where analytics anticipated needs',
 E'• تحليلات سلوك (ويب، تطبيق، نقطة بيع)\n• دراسات سوق وسلوك مستهلك\n• نماذج تنبؤية للانصراف أو الشراء\n• تخصيص ديناميكي للعرض\n• حالات استبقت فيها التحليلات الاحتياجات',
 '["No evidence of actions or data identifying customer behaviour","Measurements showing knowledge of behaviour before, during and after the value proposition, for current and potential customers","Measurements perceived for 40% of customers","Measurements perceived for 60% of customers","Measurements perceived for 80% of customers","Measurements for 100% of customers, with predictive analytics anticipating needs and translating into personalised value propositions"]'::jsonb,
 '["لا يوجد دليل على إجراءات أو بيانات تحدد سلوك العملاء","قياسات تُظهر معرفة السلوك قبل عرض القيمة وأثناءه وبعده للعملاء الحاليين والمحتملين","قياسات مُدرَكة لـ 40% من العملاء","قياسات مُدرَكة لـ 60% من العملاء","قياسات مُدرَكة لـ 80% من العملاء","قياسات لـ 100% من العملاء مع تحليلات تنبؤية تستبق الاحتياجات وتُترجم إلى عروض قيمة مخصصة"]'::jsonb),

('P 5.5','c5','5.5',5,'Behaviour','السلوك',
 'Customer decision-making plan','خطة اتخاذ قرار العملاء',
 'Knowing which factors influence the decision (price, quality, brand, recommendation) lets you invest in what truly converts and retains the end customer.',
 'معرفة العوامل المؤثرة في القرار (السعر، الجودة، العلامة، التوصية) تتيح الاستثمار فيما يحوّل العميل النهائي ويحافظ عليه فعلاً.',
 E'• Qualitative studies (focus groups, in-depth interviews)\n• Decision-driver maps per segment\n• A/B test results\n• Insight-based design process documentation\n• Strategic decisions linked to customer drivers',
 E'• دراسات نوعية (مجموعات تركيز، مقابلات معمقة)\n• خرائط محركات القرار لكل شريحة\n• نتائج اختبارات A/B\n• توثيق عملية تصميم مبنية على الرؤى\n• قرارات استراتيجية مرتبطة بمحركات العميل',
 '["No evidence of identifying the factors at play in customer decision-making","The factors at play in customer decision-making are identified","Factors identified, positively perceived at 40% across the organisation","Factors identified, positively perceived at 60% across the organisation","Factors identified, positively perceived at more than 80% across the organisation","Factors identified, positively perceived by 100% of the organisation, integrated into the strategic-decision and value-proposition design system"]'::jsonb,
 '["لا يوجد دليل على تحديد العوامل المؤثرة في اتخاذ قرار العملاء","تُحدَّد العوامل المؤثرة في اتخاذ قرار العملاء","عوامل محددة يُدركها إيجابياً 40% في المؤسسة","عوامل محددة يُدركها إيجابياً 60% في المؤسسة","عوامل محددة يُدركها إيجابياً أكثر من 80% في المؤسسة","عوامل محددة يُدركها إيجابياً 100% من المؤسسة ومدمجة في نظام القرار الاستراتيجي وتصميم عرض القيمة"]'::jsonb),

('P 5.6','c5','5.6',6,'Relationship','العلاقة',
 'Customer relationship (learning and guidance)','علاقة العملاء (التعلم والتوجيه)',
 'Supporting the customer with training and guidance maximises the value they extract from the product/service, and the resulting long-term loyalty and profitability.',
 'مرافقة العميل بالتدريب والتوجيه تعظّم القيمة التي يستخلصها من المنتج/الخدمة وما ينتج عنها من ولاء وربحية طويلي الأمد.',
 E'• Customer onboarding and training programmes\n• Learning resources (academy, webinars, materials)\n• Adoption and usage indicators per customer\n• Guidance satisfaction surveys\n• Loyalty and growth rate per trained customer',
 E'• برامج تهيئة وتدريب للعملاء\n• موارد تعلم (أكاديمية، ندوات، مواد)\n• مؤشرات تبنٍّ واستخدام لكل عميل\n• استطلاعات رضا عن التوجيه\n• معدل ولاء ونمو لكل عميل مدرَّب',
 '["No evidence of guidance management","Personalised learning and guidance projects exist for customers according to their needs and expectations","Personalised projects for 50% of customers, positively perceived in 80% of cases","Personalised projects for 75% of customers, positively perceived in 50% of cases","Personalised projects for 75% of customers, positively perceived in 80% of cases","Personalised projects for 100% of key customers, positively perceived in more than 85% of cases, with measurable results in loyalty and growth"]'::jsonb,
 '["لا يوجد دليل على إدارة التوجيه","توجد مشاريع تعلم وتوجيه مخصصة للعملاء وفق احتياجاتهم وتوقعاتهم","مشاريع مخصصة لـ 50% من العملاء يُدركها إيجابياً 80% من الحالات","مشاريع مخصصة لـ 75% من العملاء يُدركها إيجابياً 50% من الحالات","مشاريع مخصصة لـ 75% من العملاء يُدركها إيجابياً 80% من الحالات","مشاريع مخصصة لـ 100% من العملاء الرئيسيين يُدركها إيجابياً أكثر من 85% من الحالات بنتائج قابلة للقياس في الولاء والنمو"]'::jsonb),

('P 5.7','c5','5.7',7,'Communication','الاتصال',
 'Communication and direct contact with customers','الاتصال والتواصل المباشر مع العملاء',
 'Communication channels are the organisation''s visible face. Their effectiveness shapes the end customer''s perception and satisfaction at every interaction.',
 'قنوات الاتصال هي الوجه الظاهر للمؤسسة؛ وفعاليتها تحدد إدراك العميل النهائي ورضاه في كل تفاعل.',
 E'• Channel inventory (web, app, social, phone, in-person)\n• Documented omnichannel strategy\n• Response-time SLAs per channel\n• Usage and satisfaction indicators per channel\n• History of response and resolution improvements',
 E'• جرد القنوات (ويب، تطبيق، شبكات، هاتف، حضوري)\n• استراتيجية قنوات متكاملة موثقة\n• اتفاقيات زمن استجابة لكل قناة\n• مؤشرات استخدام ورضا لكل قناة\n• سجل تحسينات الاستجابة والحل',
 '["No evidence that the organisation communicates with customers","Communication channels exist for customers","Communication channels with positive impact on objectives, reaching 40% of customers","Channels with positive impact for 60% of customers","Channels with positive impact for 80% of customers","Omnichannel communication with positive impact for 100% of customers, with response times measured and systematically improved"]'::jsonb,
 '["لا يوجد دليل على تواصل المؤسسة مع العملاء","توجد قنوات اتصال للعملاء","قنوات اتصال بأثر إيجابي على الأهداف تصل إلى 40% من العملاء","قنوات بأثر إيجابي لـ 60% من العملاء","قنوات بأثر إيجابي لـ 80% من العملاء","قنوات متكاملة بأثر إيجابي لـ 100% من العملاء بأزمنة استجابة تُقاس وتُحسَّن منهجياً"]'::jsonb),

('P 5.8','c5','5.8',8,'Perception','الإدراك',
 'Perception of the value proposition and experience','إدراك عرض القيمة والتجربة',
 'What matters is not what you offer but what the customer perceives. Without measurement, proposition and reality can dangerously diverge without warning.',
 'المهم ليس ما تقدمه بل ما يدركه العميل؛ وبدون قياس قد يتباعد العرض والواقع بشكل خطير دون إنذار.',
 E'• Value-proposition perception surveys\n• NPS and spontaneous-recommendation indicators\n• Customer cases / testimonials\n• Sector NPS benchmark\n• Referral programme results',
 E'• استطلاعات إدراك عرض القيمة\n• مؤشرات NPS والتوصية التلقائية\n• حالات عملاء / شهادات\n• مقارنة NPS قطاعية\n• نتائج برامج الإحالة',
 '["No evidence that customer value propositions are reviewed and analysed","Customer-oriented value propositions are reviewed sporadically","Value proposition deployed and 40% of customers perceive it positively","Value proposition deployed and 60% of customers perceive it positively","Value proposition deployed and more than 80% perceive it positively","Value proposition deployed and 100% of key customers perceive it positively, generating spontaneous recommendation (outstanding NPS)"]'::jsonb,
 '["لا يوجد دليل على مراجعة عروض القيمة للعملاء وتحليلها","تُراجع عروض القيمة الموجهة للعملاء بشكل متفرق","عرض قيمة منشور ويدركه إيجابياً 40% من العملاء","عرض قيمة منشور ويدركه إيجابياً 60% من العملاء","عرض قيمة منشور ويدركه إيجابياً أكثر من 80%","عرض قيمة منشور يدركه إيجابياً 100% من العملاء الرئيسيين ويولد توصية تلقائية (NPS متميز)"]'::jsonb),

('P 5.9','c5','5.9',9,'Reputation','السمعة',
 'Image and reputation perceived by customers','الصورة والسمعة كما يدركها العملاء',
 'Customers also evaluate social and environmental impact. Reputation is an increasingly decisive asset in their choice to buy and to stay.',
 'يقيّم العملاء أيضاً الأثر الاجتماعي والبيئي؛ فالسمعة أصل يزداد حسماً في اختيارهم للشراء والبقاء.',
 E'• Social/environmental projects with customer participation\n• Impact report\n• Impact perception surveys\n• External sector recognitions\n• Public communication of results',
 E'• مشاريع اجتماعية/بيئية بمشاركة العملاء\n• تقرير أثر\n• استطلاعات إدراك الأثر\n• تقديرات خارجية قطاعية\n• نشر عام للنتائج',
 '["No projects with customer participation and positive social and environmental impact","Projects exist with customer participation and positive social and environmental impact","Projects positively perceived by at least 40% of the ecosystem","Projects positively perceived by at least 60% of the ecosystem","Projects positively perceived by at least 80% of the ecosystem","Projects positively perceived by 100% of the ecosystem, with external recognition and public communication of the impact generated"]'::jsonb,
 '["لا توجد مشاريع بمشاركة العملاء ذات أثر اجتماعي وبيئي إيجابي","توجد مشاريع بمشاركة العملاء ذات أثر اجتماعي وبيئي إيجابي","مشاريع يدركها إيجابياً 40% على الأقل من المنظومة","مشاريع يدركها إيجابياً 60% على الأقل من المنظومة","مشاريع يدركها إيجابياً 80% على الأقل من المنظومة","مشاريع يدركها إيجابياً 100% من المنظومة باعتراف خارجي ونشر عام للأثر المتولد"]'::jsonb),

('P 5.10','c5','5.10',10,'Improvement','التحسين',
 'Improving the value proposition and customer experience','تحسين عرض القيمة وتجربة العميل',
 'The value proposition is not static. Measuring and improving continuously sustains competitiveness in an ever-changing, ever more demanding market.',
 'عرض القيمة ليس ثابتاً؛ فالقياس والتحسين المستمران يحفظان التنافسية في سوق دائم التغير ومتزايد التطلب.',
 E'• Customer scorecard with indicators and thresholds\n• Improvement management procedure\n• Improvement plans per segment or key customer\n• Continuous improvement system (PDCA, Kaizen)\n• Annual results of the value proposition''s evolution',
 E'• لوحة مؤشرات عملاء بعتبات\n• إجراء إدارة التحسينات\n• خطط تحسين لكل شريحة أو عميل رئيسي\n• نظام تحسين مستمر (PDCA، كايزن)\n• نتائج سنوية لتطور عرض القيمة',
 '["No indicators to detect opportunities to improve the value proposition","Indicators sporadically detect improvement opportunities","Indicators and improvement plans for 40% of customers","Indicators and improvement plans for 60% of customers","Indicators and improvement plans for more than 80% of customers","Indicators and improvement plans for 100% of key customers, with a continuous-improvement cycle embedded in the management system"]'::jsonb,
 '["لا توجد مؤشرات لرصد فرص تحسين عرض القيمة","مؤشرات ترصد فرص التحسين بشكل متفرق","مؤشرات وخطط تحسين لـ 40% من العملاء","مؤشرات وخطط تحسين لـ 60% من العملاء","مؤشرات وخطط تحسين لأكثر من 80% من العملاء","مؤشرات وخطط تحسين لـ 100% من العملاء الرئيسيين بدورة تحسين مستمر مدمجة في نظام الإدارة"]'::jsonb)
on conflict (code) do update set
  block_en = excluded.block_en, block_ar = excluded.block_ar,
  question_en = excluded.question_en, question_ar = excluded.question_ar,
  context_en = excluded.context_en, context_ar = excluded.context_ar,
  evidence_en = excluded.evidence_en, evidence_ar = excluded.evidence_ar,
  levels_en = excluded.levels_en, levels_ar = excluded.levels_ar,
  sort = excluded.sort;
-- VERIFICAR: select count(*) from assessment_questions;  → 50 (C1..C5)
