-- ============================================================================
-- ORBITAL 360 — Migration 07d · SEED Criterios 6-7 (EN/AR) — re-ejecutable
-- C6 · Sustainability & CSR — C7 · Performance & Transformation
-- ============================================================================
insert into public.assessment_questions
  (code, criterion_code, ref, sort, block_en, block_ar, question_en, question_ar,
   context_en, context_ar, evidence_en, evidence_ar, levels_en, levels_ar)
values
('P 6.1','c6','6.1',1,'CSR','المسؤولية الاجتماعية',
 'Material aspects of CSR','الجوانب الجوهرية للمسؤولية الاجتماعية',
 'Material aspects are the topics with the greatest impact on the business and stakeholders. Focusing on them makes CSR effective, not decorative.',
 'الجوانب الجوهرية هي الموضوعات الأكثر أثراً في الأعمال وأصحاب المصلحة؛ والتركيز عليها يجعل المسؤولية الاجتماعية فعالة لا شكلية.',
 E'• Documented materiality analysis\n• Published materiality matrix\n• Action plan derived from material aspects\n• Annual sustainability report (GRI, SASB)\n• External verification of the report',
 E'• تحليل جوهرية موثق\n• مصفوفة جوهرية منشورة\n• خطة عمل مشتقة من الجوانب الجوهرية\n• تقرير استدامة سنوي (GRI، SASB)\n• تحقق خارجي من التقرير',
 '["No plans for assessing material aspects in CSR","Assessment plans exist but are barely systematised","Assessment plans covering 40% of the ecosystem","Plans covering 60% of the ecosystem","Plans covering more than 80% of the ecosystem","Plans covering 100% of the ecosystem, with a sustainability report periodically published to international standards (GRI, SASB or similar)"]'::jsonb,
 '["لا توجد خطط لتقييم الجوانب الجوهرية في المسؤولية الاجتماعية","توجد خطط تقييم لكنها قليلة المنهجية","خطط تقييم تشمل 40% من المنظومة","خطط تشمل 60% من المنظومة","خطط تشمل أكثر من 80% من المنظومة","خطط تغطي 100% من المنظومة مع نشر دوري لتقرير استدامة وفق المعايير الدولية (GRI أو SASB أو مماثل)"]'::jsonb),

('P 6.2','c6','6.2',2,'SDGs','أهداف التنمية المستدامة',
 'Strategic alignment with the SDGs','الاتساق الاستراتيجي مع أهداف التنمية المستدامة',
 'The SDGs are the global sustainable-development framework. Aligning strategy with them eases reporting, financing and reputation in today''s global ecosystem.',
 'أهداف التنمية المستدامة هي الإطار العالمي للتنمية المستدامة؛ ومواءمة الاستراتيجية معها تسهّل الإبلاغ والتمويل والسمعة في المنظومة العالمية اليوم.',
 E'• Strategy map with SDGs assigned to each line\n• Specific indicators per SDG\n• Published SDG progress report\n• Stakeholder reporting (Global Compact or others)\n• Concrete projects linked to SDG targets',
 E'• خريطة استراتيجية بأهداف تنمية لكل خط\n• مؤشرات محددة لكل هدف\n• تقرير تقدم منشور لأهداف التنمية\n• إبلاغ أصحاب المصلحة (الميثاق العالمي أو غيره)\n• مشاريع ملموسة مرتبطة بغايات الأهداف',
 '["No plans integrating the SDGs","The organisation analyses and integrates into its strategy the SDGs it can contribute to","Deploys and aligns at least 40% of its strategic lines with the SDGs","Deploys and aligns at least 60% of its strategic lines with the SDGs","Deploys and aligns more than 80% of its strategic lines with the SDGs","Deploys and aligns 100% of its strategic lines with the SDGs, with indicators measured systematically and reported to external stakeholders"]'::jsonb,
 '["لا توجد خطط تدمج أهداف التنمية المستدامة","تحلل المؤسسة وتدمج في استراتيجيتها الأهداف التي يمكنها الإسهام فيها","تنشر وتوائم 40% على الأقل من خطوطها الاستراتيجية مع الأهداف","تنشر وتوائم 60% على الأقل من خطوطها الاستراتيجية مع الأهداف","تنشر وتوائم أكثر من 80% من خطوطها الاستراتيجية مع الأهداف","تنشر وتوائم 100% من خطوطها الاستراتيجية مع الأهداف بمؤشرات تُقاس منهجياً وتُبلغ لأصحاب مصلحة خارجيين"]'::jsonb),

('P 6.3','c6','6.3',3,'Environment','البيئة',
 'Environmental development plan','خطة التطوير البيئي',
 'Environmental impact is a legal, social and investor requirement. Managing it actively cuts operational risk and opens new, differentiating business opportunities.',
 'الأثر البيئي مطلب قانوني واجتماعي واستثماري؛ وإدارته بفاعلية تخفض المخاطر التشغيلية وتفتح فرص أعمال جديدة ومميزة.',
 E'• Environmental policy\n• Environmental plan with quantitative objectives\n• Environmental footprint indicators (carbon, water, waste)\n• ISO 14001 / EMAS certificates\n• Decarbonisation plan with a mid-term horizon (SBTi)',
 E'• سياسة بيئية\n• خطة بيئية بأهداف كمية\n• مؤشرات البصمة البيئية (كربون، ماء، نفايات)\n• شهادات ISO 14001 / EMAS\n• خطة إزالة كربون بأفق متوسط (SBTi)',
 '["No evidence of environmental responsibility plans","Environmental responsibility plans exist enabling impact minimisation","Measurements showing impact is minimised for 40% of the ecosystem","Measurements for 60% of the ecosystem","Measurements for 80% of the ecosystem","Measurements for 100% of the ecosystem, with external certifications (ISO 14001, EMAS or similar) and mid-term net-zero targets"]'::jsonb,
 '["لا يوجد دليل على خطط مسؤولية بيئية","توجد خطط مسؤولية بيئية تتيح تقليل الأثر","قياسات تُظهر تقليل الأثر لـ 40% من المنظومة","قياسات لـ 60% من المنظومة","قياسات لـ 80% من المنظومة","قياسات لـ 100% من المنظومة بشهادات خارجية (ISO 14001 أو EMAS أو مماثلة) وأهداف حياد كربوني متوسطة المدى"]'::jsonb),

('P 6.4','c6','6.4',4,'Communication','الاتصال',
 'Clear, transparent communication with the ecosystem','اتصال واضح وشفاف مع المنظومة',
 'Transparency with the ecosystem builds trust. Without clear communication, good practices go unnoticed and generate neither reputation nor shared value.',
 'الشفافية مع المنظومة تبني الثقة؛ وبدون اتصال واضح تمر الممارسات الجيدة دون أن تُلحظ فلا تولد سمعة ولا قيمة مشتركة.',
 E'• Stakeholder communication plan\n• Published integrated or sustainability report\n• Open dialogue channels (consultations, webinars, forums)\n• Transparency perception surveys\n• External transparency evaluation (Dow Jones, FTSE4Good)',
 E'• خطة اتصال بأصحاب المصلحة\n• تقرير متكامل أو استدامة منشور\n• قنوات حوار مفتوحة (مشاورات، ندوات، منتديات)\n• استطلاعات إدراك الشفافية\n• تقييم شفافية خارجي (داو جونز، FTSE4Good)',
 '["No plans managing clear, transparent communication with the ecosystem","Evidence of clear, transparent communication with the ecosystem","Communication plans positively perceived by 40% of the ecosystem","Plans perceived by 60% of the ecosystem","Plans perceived by more than 80% of the ecosystem","Plans perceived by 100% of the ecosystem, with a public integrated report and active stakeholder dialogue"]'::jsonb,
 '["لا توجد خطط تدير اتصالاً واضحاً وشفافاً مع المنظومة","دلائل على اتصال واضح وشفاف مع المنظومة","خطط اتصال يدركها إيجابياً 40% من المنظومة","خطط يدركها 60% من المنظومة","خطط يدركها أكثر من 80% من المنظومة","خطط يدركها 100% من المنظومة مع تقرير عام متكامل وحوار نشط مع أصحاب المصلحة"]'::jsonb),

('P 6.5','c6','6.5',5,'Reputation','السمعة',
 'Ecosystem perception of reputation','إدراك المنظومة للسمعة',
 'Reputation takes years to build and can be lost in a day. Measuring it lets you anticipate risks and protect this most valuable intangible asset.',
 'السمعة تُبنى في سنوات وقد تُفقد في يوم؛ وقياسها يتيح استباق المخاطر وحماية هذا الأصل غير الملموس البالغ القيمة.',
 E'• Corporate reputation studies (RepTrak or similar)\n• Positioning in sector rankings (Merco, Best Place to Work)\n• Documented community-engagement projects\n• Social impact reports\n• Recognised certifications (B Corp, EFR, etc.)',
 E'• دراسات سمعة مؤسسية (RepTrak أو مماثل)\n• مكانة في تصنيفات قطاعية (Merco، أفضل مكان عمل)\n• مشاريع تفاعل مجتمعي موثقة\n• تقارير أثر اجتماعي\n• شهادات معترف بها (B Corp، EFR، إلخ)',
 '["No measurements demonstrating the ecosystem''s perception of reputation and image","Projects exist demonstrating the organisation''s commitment to its ecosystem","Commitment projects positively perceived by 40% of the ecosystem","Projects positively perceived by 60% of the ecosystem","Projects positively perceived by 80% of the ecosystem","Projects positively perceived by 100% of the ecosystem, with presence in sector reputation rankings and recognised certifications"]'::jsonb,
 '["لا توجد قياسات تُظهر إدراك المنظومة للسمعة والصورة","توجد مشاريع تُظهر التزام المؤسسة تجاه منظومتها","مشاريع التزام يدركها إيجابياً 40% من المنظومة","مشاريع يدركها إيجابياً 60% من المنظومة","مشاريع يدركها إيجابياً 80% من المنظومة","مشاريع يدركها إيجابياً 100% من المنظومة مع حضور في تصنيفات السمعة القطاعية وشهادات معترف بها"]'::jsonb),

('P 6.6','c6','6.6',6,'Social experience','التجربة الاجتماعية',
 'Social value and experience of the ecosystem','القيمة والتجربة الاجتماعية للمنظومة',
 'The value the organisation brings to society goes beyond the product. The social experience is part of the extended proposition.',
 'القيمة التي تقدمها المؤسسة للمجتمع تتجاوز المنتج؛ فالتجربة الاجتماعية جزء من العرض الموسع.',
 E'• Social and economic impact studies (SROI or others)\n• Public impact report\n• Ecosystem surveys on perceived social value\n• Annual social and economic footprint calculation\n• External impact audit',
 E'• دراسات أثر اجتماعي واقتصادي (SROI أو غيرها)\n• تقرير أثر عام\n• استطلاعات للمنظومة حول القيمة الاجتماعية المُدرَكة\n• حساب سنوي للبصمة الاجتماعية والاقتصادية\n• تدقيق خارجي للأثر',
 '["No evidence that the social experience generated by the value propositions is reviewed","Ecosystem-oriented value propositions are reviewed sporadically","Measurements of the value proposition''s positive impact perceived at 40%","Positive-impact measurements perceived at 60%","Positive-impact measurements perceived at more than 80%","Positive-impact measurements perceived by 100% of the ecosystem, with public disclosure of the social and economic footprint generated"]'::jsonb,
 '["لا يوجد دليل على مراجعة التجربة الاجتماعية التي ولدتها عروض القيمة","تُراجع عروض القيمة الموجهة للمنظومة بشكل متفرق","قياسات للأثر الإيجابي لعرض القيمة مُدرَكة بنسبة 40%","قياسات أثر إيجابي مُدرَكة بنسبة 60%","قياسات أثر إيجابي مُدرَكة بأكثر من 80%","قياسات أثر إيجابي يدركها 100% من المنظومة مع نشر عام لحساب البصمة الاجتماعية والاقتصادية المتولدة"]'::jsonb),

('P 6.7','c6','6.7',7,'Regulatory framework','الإطار التنظيمي',
 'Institutional and regulatory changes','التغيرات المؤسسية والتنظيمية',
 'The regulatory framework changes constantly. Anticipating avoids penalties and lets you influence the regulation that will soon affect the sector.',
 'الإطار التنظيمي يتغير باستمرار؛ والاستباق يجنب العقوبات ويتيح التأثير في التنظيم الذي سيمس القطاع قريباً وعلى المدى المتوسط.',
 E'• Regulatory watch procedure\n• Person or area responsible for compliance\n• Register of regulatory changes and actions taken\n• Participation in sector groups / public consultations\n• Public positioning on regulatory changes',
 E'• إجراء رصد تنظيمي\n• شخص أو جهة مسؤولة عن الامتثال\n• سجل التغيرات التنظيمية والإجراءات المتخذة\n• مشاركة في مجموعات قطاعية / مشاورات عامة\n• موقف عام من التغيرات التنظيمية',
 '["No resources to identify, update and manage governmental and regulatory changes","Governmental and regulatory changes are identified, updated and managed, but without evidence","At least 40% of changes identified, updated and managed with agility","At least 60% of changes identified, updated and managed with agility","More than 80% of changes identified, updated and managed with agility","100% of changes identified, updated and managed with agility, with a proactive anticipation system and participation in public consultations or sector forums"]'::jsonb,
 '["لا توجد موارد لتحديد التغيرات الحكومية والتنظيمية وتحديثها وإدارتها","تُحدَّد التغيرات الحكومية والتنظيمية وتُحدَّث وتُدار لكن دون أدلة","تُحدَّد وتُدار 40% على الأقل من التغيرات برشاقة","تُحدَّد وتُدار 60% على الأقل من التغيرات برشاقة","تُحدَّد وتُدار أكثر من 80% من التغيرات برشاقة","تُحدَّد وتُدار 100% من التغيرات برشاقة مع نظام استباق فاعل ومشاركة في المشاورات العامة أو المنتديات القطاعية"]'::jsonb),

('P 6.8','c6','6.8',8,'Social experience','التجربة الاجتماعية',
 'Updates to the value proposition and social experience','تحديثات عرض القيمة والتجربة الاجتماعية',
 'The social context evolves, and the social value proposition must be updated periodically to stay relevant and legitimate before a changing ecosystem.',
 'يتطور السياق الاجتماعي، ويجب تحديث عرض القيمة الاجتماعية دورياً للحفاظ على الملاءمة والمشروعية أمام منظومة متغيرة.',
 E'• Annual review of material aspects\n• Active-listening sessions with ecosystem groups\n• Quantitative social-perception measurements\n• Report with the evolution of material aspects\n• Post-review action plan',
 E'• مراجعة سنوية للجوانب الجوهرية\n• جلسات إصغاء فعّال مع فئات المنظومة\n• قياسات كمية للإدراك الاجتماعي\n• تقرير بتطور الجوانب الجوهرية\n• خطة عمل بعد المراجعة',
 '["No evidence that the social experience is identified","Measurements show the organisation knows the social experience of the identified material aspects","Measurements positively perceived for 40% of the ecosystem","Measurements positively perceived for 60% of the ecosystem","Measurements positively perceived for 80% of the ecosystem","Measurements positively perceived for 100% of the ecosystem, with material aspects periodically reviewed as the context evolves"]'::jsonb,
 '["لا يوجد دليل على تحديد التجربة الاجتماعية","قياسات تُظهر معرفة المؤسسة بالتجربة الاجتماعية للجوانب الجوهرية المحددة","قياسات يدركها إيجابياً 40% من المنظومة","قياسات يدركها إيجابياً 60% من المنظومة","قياسات يدركها إيجابياً 80% من المنظومة","قياسات يدركها إيجابياً 100% من المنظومة مع مراجعة دورية للجوانب الجوهرية وفق تطور السياق"]'::jsonb),

('P 6.9','c6','6.9',9,'Good practices','الممارسات الجيدة',
 'Sharing good practices','مشاركة الممارسات الجيدة',
 'Sharing good practices multiplies the positive impact on the ecosystem and positions the organisation as an externally recognised sector benchmark with growing reputation.',
 'مشاركة الممارسات الجيدة تضاعف الأثر الإيجابي في المنظومة وترسّخ المؤسسة كمرجعية قطاعية معترف بها خارجياً بسمعة متنامية.',
 E'• Repository of shared good practices\n• Talks at sector conferences\n• Published case studies\n• External awards for good practices\n• Public access to methodologies or guidance documents',
 E'• مستودع ممارسات جيدة مشتركة\n• محاضرات في مؤتمرات قطاعية\n• دراسات حالة منشورة\n• جوائز خارجية للممارسات الجيدة\n• إتاحة عامة للمنهجيات أو الوثائق الإرشادية',
 '["No evidence that the organisation shares good practices","Evidence that the organisation shares good practices","Good practices positively perceived by 40% of the ecosystem","Good practices positively perceived by 60% of the ecosystem","Good practices positively perceived by more than 80% of the ecosystem","Good practices positively perceived by 100% of the ecosystem, with external recognition (awards, published case studies, talks at sector forums)"]'::jsonb,
 '["لا يوجد دليل على مشاركة المؤسسة للممارسات الجيدة","دلائل على مشاركة المؤسسة للممارسات الجيدة","ممارسات جيدة يدركها إيجابياً 40% من المنظومة","ممارسات جيدة يدركها إيجابياً 60% من المنظومة","ممارسات جيدة يدركها إيجابياً أكثر من 80% من المنظومة","ممارسات جيدة يدركها إيجابياً 100% من المنظومة باعتراف خارجي (جوائز، دراسات حالة منشورة، محاضرات في منتديات قطاعية)"]'::jsonb),

('P 6.10','c6','6.10',10,'Sustainable investment','الاستثمار المستدام',
 'Sustainable investment plans','خطط الاستثمار المستدام',
 'Investment decisions shape the future. Applying ESG criteria ensures financial sustainability and real alignment with the organisation''s declared values.',
 'قرارات الاستثمار تصنع المستقبل؛ وتطبيق معايير ESG يضمن الاستدامة المالية والاتساق الحقيقي مع القيم المعلنة للمؤسسة.',
 E'• 3-5 year financial plan\n• Investment policy with ESG criteria\n• Short- and long-term liquidity analysis\n• Report with strategic investment results\n• Adherence to responsible-investment principles (UNPRI)',
 E'• خطة مالية لثلاث إلى خمس سنوات\n• سياسة استثمار بمعايير ESG\n• تحليل سيولة قصير وطويل المدى\n• تقرير بنتائج الاستثمارات الاستراتيجية\n• الانضمام إلى مبادئ الاستثمار المسؤول (UNPRI)',
 '["No investment plans","Investment and financing plans exist identifying tangible and intangible assets and analysing short- and long-term liquidity needs","Plans positively perceived by 50% of the ecosystem, demonstrating 50% of strategic results","Plans perceived by 50% of the ecosystem, demonstrating 75% of strategic results","Plans perceived by 75% of the ecosystem, demonstrating 75% of strategic results","Plans perceived by 100% of the ecosystem, demonstrating more than 90% of strategic results and applying ESG criteria to every investment decision"]'::jsonb,
 '["لا توجد خطط استثمار","توجد خطط استثمار وتمويل تحدد الأصول الملموسة وغير الملموسة وتحلل احتياجات السيولة قصيرة وطويلة المدى","خطط يدركها إيجابياً 50% من المنظومة وتُثبت 50% من النتائج الاستراتيجية","خطط يدركها 50% من المنظومة وتُثبت 75% من النتائج الاستراتيجية","خطط يدركها 75% من المنظومة وتُثبت 75% من النتائج الاستراتيجية","خطط يدركها 100% من المنظومة وتُثبت أكثر من 90% من النتائج الاستراتيجية وتطبق معايير ESG في كل قرارات الاستثمار"]'::jsonb),

-- ============== C7 · PERFORMANCE & TRANSFORMATION ==============
('P 7.1','c7','7.1',1,'Processes','العمليات',
 'Identifying and deploying key processes','تحديد العمليات الرئيسية ونشرها',
 'Key processes are the operational backbone. Identifying and measuring them is the basis of any systematic improvement and real organisational efficiency.',
 'العمليات الرئيسية هي العمود الفقري التشغيلي؛ وتحديدها وقياسها أساس أي تحسين منهجي وكفاءة مؤسسية حقيقية.',
 E'• Process map identifying key processes\n• Process sheets with indicators and owners\n• Scorecard tracking the indicators\n• Periodic process-review procedure\n• Process improvement reports',
 E'• خريطة عمليات تحدد العمليات الرئيسية\n• بطاقات عمليات بمؤشرات ومسؤولين\n• لوحة مؤشرات لمتابعة القياسات\n• إجراء مراجعة دورية للعمليات\n• تقارير تحسين العمليات',
 '["No evidence that key processes are identified in the organisation","Key processes are identified and measurement indicators established for improvement","Key processes with indicators enabling the analysis and improvement of 40% of them","Key processes with indicators enabling the analysis and improvement of 60% of them","Key processes with indicators enabling the analysis and improvement of 80% of them","Key processes with indicators enabling the analysis and improvement of 100% of them, with systematic review cycles"]'::jsonb,
 '["لا يوجد دليل على تحديد العمليات الرئيسية في المؤسسة","تُحدَّد العمليات الرئيسية وتوضع مؤشرات قياس للتحسين","عمليات رئيسية بمؤشرات تتيح تحليل 40% منها وتحسينها","عمليات رئيسية بمؤشرات تتيح تحليل 60% منها وتحسينها","عمليات رئيسية بمؤشرات تتيح تحليل 80% منها وتحسينها","عمليات رئيسية بمؤشرات تتيح تحليل 100% منها وتحسينها بدورات مراجعة منهجية"]'::jsonb),

('P 7.2','c7','7.2',2,'Processes','العمليات',
 'Risk management and control in processes','إدارة المخاطر وضبطها في العمليات',
 'Every process carries risk. Managing it proactively avoids costly interruptions and reputational damage, and lets you anticipate corrective action in time.',
 'كل عملية تحمل مخاطر؛ وإدارتها استباقياً تجنب الانقطاعات المكلفة والأضرار السمعية وتتيح استباق الإجراءات التصحيحية في الوقت المناسب.',
 E'• Risk map per process\n• Risk-management procedure (ISO 31000)\n• Risk-treatment plans\n• Efficiency/effectiveness indicators per process\n• ISO 31000 certification or equivalent',
 E'• خريطة مخاطر لكل عملية\n• إجراء إدارة مخاطر (ISO 31000)\n• خطط معالجة المخاطر\n• مؤشرات كفاءة/فعالية لكل عملية\n• شهادة ISO 31000 أو ما يعادلها',
 '["No evidence of projects oriented to risk management","The organisation has systematic processes oriented to risk management","Systematic processes with demonstrated efficiency and effectiveness in 40% of processes","Systematic processes with demonstrated efficiency and effectiveness in 60% of processes","Systematic processes with demonstrated efficiency and effectiveness in 80% of processes","Systematic processes with demonstrated efficiency and effectiveness in 100% of processes, with a certified risk-management system (ISO 31000 or similar)"]'::jsonb,
 '["لا يوجد دليل على مشاريع موجهة لإدارة المخاطر","لدى المؤسسة عمليات منهجية موجهة لإدارة المخاطر","عمليات منهجية بكفاءة وفعالية مثبتة في 40% من العمليات","عمليات منهجية بكفاءة وفعالية مثبتة في 60% من العمليات","عمليات منهجية بكفاءة وفعالية مثبتة في 80% من العمليات","عمليات منهجية بكفاءة وفعالية مثبتة في 100% من العمليات بنظام إدارة مخاطر معتمد (ISO 31000 أو مماثل)"]'::jsonb),

('P 7.3','c7','7.3',3,'Transformation','التحول',
 'Turning challenges and opportunities into transformation projects','تحويل التحديات والفرص إلى مشاريع تحول',
 'Turning challenges and opportunities into concrete projects separates declared strategy from real transformation, measurable in tangible, externally communicable results.',
 'تحويل التحديات والفرص إلى مشاريع ملموسة يفصل الاستراتيجية المعلنة عن التحول الحقيقي القابل للقياس بنتائج ملموسة يمكن إيصالها خارجياً.',
 E'• Transformation project portfolio (PMO)\n• Sponsors and monitoring committees\n• Stakeholder perception surveys\n• Transformation scorecard\n• Success stories with quantified impact',
 E'• محفظة مشاريع تحول (PMO)\n• رعاة ولجان متابعة\n• استطلاعات إدراك للأطراف المعنية\n• لوحة مؤشرات تحول\n• قصص نجاح بأثر مُكمّى',
 '["No evidence that transformation projects exist and are properly managed","Transformation projects exist and are properly managed","Projects based on challenges/opportunities, positively perceived by 40% of interested parties","Projects positively perceived by 60% of interested parties","Projects positively perceived by 80% of interested parties","Projects positively perceived by 100% of interested parties, with measurable results in innovation and competitiveness"]'::jsonb,
 '["لا يوجد دليل على وجود مشاريع تحول وإدارتها بشكل ملائم","توجد مشاريع تحول تُدار بشكل ملائم","مشاريع مبنية على التحديات/الفرص يدركها إيجابياً 40% من الأطراف المعنية","مشاريع يدركها إيجابياً 60% من الأطراف المعنية","مشاريع يدركها إيجابياً 80% من الأطراف المعنية","مشاريع يدركها إيجابياً 100% من الأطراف المعنية بنتائج قابلة للقياس في الابتكار والتنافسية"]'::jsonb),

('P 7.4','c7','7.4',4,'Transformation','التحول',
 'Innovation management','إدارة الابتكار',
 'Agile methodologies speed up innovation, cut the risk of failure and let you validate ideas with real customers in short, iterative learning cycles.',
 'المنهجيات الرشيقة تسرّع الابتكار وتخفض مخاطر الفشل وتتيح التحقق من الأفكار مع عملاء حقيقيين في دورات تعلم قصيرة وتكرارية.',
 E'• Documented agile methodologies (Scrum, Design Thinking)\n• Inventory of innovation projects per methodology\n• Agile methodology training\n• Innovation management system (UNE 166002)\n• Results of projects run with agile methodologies',
 E'• منهجيات رشيقة موثقة (سكروم، التفكير التصميمي)\n• جرد مشاريع الابتكار حسب المنهجية\n• تدريب على المنهجيات الرشيقة\n• نظام إدارة ابتكار (UNE 166002)\n• نتائج المشاريع المنفذة بمنهجيات رشيقة',
 '["No evidence that innovation is managed with a suitable methodology","Agile methodologies for innovation management exist sporadically","40% of innovation projects are managed with agile methodologies","60% of innovation projects are managed with agile methodologies","80% of innovation projects are managed with agile methodologies","100% of innovation projects are managed with agile methodologies, with a recognised innovation-management system (UNE 166002 or similar)"]'::jsonb,
 '["لا يوجد دليل على إدارة الابتكار بمنهجية ملائمة","توجد منهجيات رشيقة لإدارة الابتكار بشكل متفرق","تُدار 40% من مشاريع الابتكار بمنهجيات رشيقة","تُدار 60% من مشاريع الابتكار بمنهجيات رشيقة","تُدار 80% من مشاريع الابتكار بمنهجيات رشيقة","تُدار 100% من مشاريع الابتكار بمنهجيات رشيقة بنظام إدارة ابتكار معترف به (UNE 166002 أو مماثل)"]'::jsonb),

('P 7.5','c7','7.5',5,'Life cycle','دورة الحياة',
 'Life-cycle management (products/services)','إدارة دورة الحياة (المنتجات/الخدمات)',
 'Managing the full product/service life cycle cuts environmental impact, optimises resources and meets the growing expectations of today''s market and regulators.',
 'إدارة دورة الحياة الكاملة للمنتج/الخدمة تخفض الأثر البيئي وتحسّن الموارد وتلبي التوقعات المتنامية للسوق والمنظمين اليوم.',
 E'• Life-cycle analysis (LCA) of main products/services\n• Environmental and health impact assessment procedure\n• Environmental labelling (carbon footprint, ecolabels)\n• External communication of the LCA\n• Stakeholder perception surveys',
 E'• تحليل دورة حياة (LCA) للمنتجات/الخدمات الرئيسية\n• إجراء تقييم الأثر البيئي والصحي\n• وسم بيئي (بصمة كربونية، علامات بيئية)\n• إيصال خارجي لنتائج التحليل\n• استطلاعات إدراك لأصحاب المصلحة',
 '["No evidence of product/service life-cycle management and its environmental/health impact","Evidence of life-cycle management and of its impact on the environment and health","Life-cycle management positively perceived by 40% of key stakeholder groups","Management perceived by 60% of key stakeholder groups","Management perceived by 80% of key stakeholder groups","Management perceived by 100% of key stakeholder groups, with a documented, externally communicated LCA"]'::jsonb,
 '["لا يوجد دليل على إدارة دورة حياة المنتجات/الخدمات وأثرها البيئي/الصحي","دلائل على إدارة دورة الحياة وأثرها على البيئة والصحة","إدارة دورة حياة يدركها إيجابياً 40% من فئات أصحاب المصلحة الرئيسية","إدارة يدركها 60% من فئات أصحاب المصلحة الرئيسية","إدارة يدركها 80% من فئات أصحاب المصلحة الرئيسية","إدارة يدركها 100% من فئات أصحاب المصلحة الرئيسية بتحليل دورة حياة موثق ومُبلغ خارجياً"]'::jsonb),

('P 7.6','c7','7.6',6,'Assets','الأصول',
 'Asset management','إدارة الأصول',
 'Physical and intangible assets are both investment and risk. Managing them well optimises cost, useful life and environmental impact throughout their operating span.',
 'الأصول المادية وغير الملموسة استثمار ومخاطرة معاً؛ وإدارتها الجيدة تحسّن التكلفة والعمر التشغيلي والأثر البيئي طوال مدة تشغيلها.',
 E'• Asset inventory (tangible and intangible)\n• Asset maintenance and renewal plan\n• Asset environmental and health impact analysis\n• ISO 55001 procedure (asset management)\n• Stakeholder perception surveys',
 E'• جرد الأصول (ملموسة وغير ملموسة)\n• خطة صيانة الأصول وتجديدها\n• تحليل الأثر البيئي والصحي للأصول\n• إجراء ISO 55001 (إدارة الأصول)\n• استطلاعات إدراك للأطراف المعنية',
 '["No evidence of asset management","Evidence of asset management","Assets managed with reviewed environmental/health impact, perceived by 40% of interested parties","Assets managed, perceived by 60% of interested parties","Assets managed, perceived by 80% of interested parties","Assets managed, perceived by 100% of interested parties, with a recognised asset-management system (ISO 55001 or similar)"]'::jsonb,
 '["لا يوجد دليل على إدارة الأصول","دلائل على إدارة الأصول","أصول مُدارة بأثر بيئي/صحي مُراجَع يدركها 40% من الأطراف المعنية","أصول مُدارة يدركها 60% من الأطراف المعنية","أصول مُدارة يدركها 80% من الأطراف المعنية","أصول مُدارة يدركها 100% من الأطراف المعنية بنظام إدارة أصول معترف به (ISO 55001 أو مماثل)"]'::jsonb),

('P 7.7','c7','7.7',7,'Resources','الموارد',
 'Financial resources','الموارد المالية',
 'Financial resources sustain both current operations and the future. Planning them is a necessary condition for continuity and sustained mid-term growth.',
 'الموارد المالية تدعم التشغيل الحالي والمستقبل معاً؛ وتخطيطها شرط ضروري للاستمرارية والنمو المستدام متوسط المدى.',
 E'• Multi-year financial plan\n• Analysis of diversified financing sources\n• Budget execution history\n• Future investment plan\n• Financial health indicators (ratios, liquidity)',
 E'• خطة مالية متعددة السنوات\n• تحليل مصادر تمويل متنوعة\n• سجل تنفيذ الميزانية\n• خطة استثمارات مستقبلية\n• مؤشرات صحة مالية (نسب، سيولة)',
 '["No evidence of financial resources guaranteeing current success and future investment","Financial resources guaranteeing success are identified","Resources guaranteeing success and future investment in 40% of cases","Resources guaranteeing success and future investment in 60% of cases","Resources guaranteeing success and future investment in 80% of cases","Resources guaranteeing success and future investment in 100% of cases, with a 5+ year financial plan and diversified sources"]'::jsonb,
 '["لا تظهر موارد مالية تضمن النجاح الحالي والاستثمار المستقبلي","تُحدَّد موارد مالية تضمن النجاح","موارد تضمن النجاح والاستثمار المستقبلي في 40% من الحالات","موارد تضمن النجاح والاستثمار المستقبلي في 60% من الحالات","موارد تضمن النجاح والاستثمار المستقبلي في 80% من الحالات","موارد تضمن النجاح والاستثمار المستقبلي في 100% من الحالات بخطة مالية لخمس سنوات فأكثر ومصادر متنوعة"]'::jsonb),

('P 7.8','c7','7.8',8,'Resources','الموارد',
 'New technologies','التقنيات الجديدة',
 'Emerging technologies redefine sectors. Ignoring them is a competitive risk; adopting them judiciously is a sustainable advantage and future strategic differentiation.',
 'التقنيات الناشئة تعيد تعريف القطاعات؛ وتجاهلها مخاطرة تنافسية، وتبنّيها بحكمة ميزة مستدامة وتمايز استراتيجي مستقبلي.',
 E'• Technology plan with a time horizon\n• Technology watch procedure\n• Investment in R&D&I / new technologies\n• Technology prototyping lab or area\n• Cases of emerging-technology adoption with results',
 E'• خطة تقنية بأفق زمني\n• إجراء رصد تقني\n• استثمار في البحث والتطوير والابتكار / التقنيات الجديدة\n• مختبر أو وحدة نمذجة تقنية\n• حالات تبنّي تقنيات ناشئة بنتائجها',
 '["No evidence that the organisation evaluates the potential of new technologies to support value creation","Evidence that the organisation evaluates the potential of new technologies","The organisation deploys and reviews 40% of the technology-improvement plan, measuring its effectiveness","Deploys and reviews 60% of the plan","Deploys and reviews 80% of the plan","Deploys and reviews 100% of the plan, with active technology watch and prototyping of emerging technologies"]'::jsonb,
 '["لا يوجد دليل على تقييم المؤسسة لإمكانات التقنيات الجديدة لدعم خلق القيمة","دلائل على تقييم المؤسسة لإمكانات التقنيات الجديدة","تنشر المؤسسة وتراجع 40% من خطة التحسين التقني وتقيس فعاليتها","تنشر وتراجع 60% من الخطة","تنشر وتراجع 80% من الخطة","تنشر وتراجع 100% من الخطة برصد تقني نشط ونمذجة للتقنيات الناشئة"]'::jsonb),

('P 7.9','c7','7.9',9,'Security','الأمن',
 'Information and data security','أمن المعلومات والبيانات',
 'Data is a critical asset and a target of cyberattacks. Managing and protecting it is now a prerequisite for operating in any sector and a growing legal requirement.',
 'البيانات أصل حرج وهدف للهجمات السيبرانية؛ وإدارتها وحمايتها باتتا شرطاً مسبقاً للعمل في أي قطاع ومطلباً قانونياً متنامياً.',
 E'• Information security policy\n• Security risk analysis\n• Cybersecurity training plan for all people\n• ISO 27001 certificate or equivalent national scheme\n• Periodic audits with published results',
 E'• سياسة أمن معلومات\n• تحليل مخاطر أمنية\n• خطة تدريب على الأمن السيبراني لجميع الأفراد\n• شهادة ISO 27001 أو نظام وطني معادل\n• تدقيقات دورية بنتائج منشورة',
 '["No evidence that the organisation manages information and data security","Evidence that the organisation manages information and data security","The organisation sets objectives for information and data security","Objectives tied to security risks, with planning and follow-up","Objectives tied to the risks, with planning, follow-up and systematic training for 80% of people","Certified management system (ISO 27001 or equivalent), with periodic audits and transparent communication of incidents to the ecosystem"]'::jsonb,
 '["لا يوجد دليل على إدارة المؤسسة لأمن المعلومات والبيانات","دلائل على إدارة المؤسسة لأمن المعلومات والبيانات","تضع المؤسسة أهدافاً لأمن المعلومات والبيانات","أهداف مرتبطة بمخاطر الأمن مع تخطيط ومتابعة","أهداف مرتبطة بالمخاطر مع تخطيط ومتابعة وتدريب منهجي لـ 80% من الأفراد","نظام إدارة معتمد (ISO 27001 أو معادل) بتدقيقات دورية وإبلاغ شفاف للمنظومة عن الحوادث"]'::jsonb),

('P 7.10','c7','7.10',10,'Environmental impact','الأثر البيئي',
 'Environmental impact','الأثر البيئي',
 'Reducing environmental impact is an ethical responsibility, a regulatory demand and a competitiveness factor for customers and investors ever more demanding on sustainability.',
 'خفض الأثر البيئي مسؤولية أخلاقية ومطلب تنظيمي وعامل تنافسية أمام عملاء ومستثمرين يزدادون تطلباً في الاستدامة.',
 E'• Environmental policy and plan\n• Quantitative environmental footprint indicators\n• Decarbonisation plan with targets (SBTi)\n• ISO 14001 or EMAS certificate\n• CDP, GRI, TCFD or similar reporting',
 E'• سياسة وخطة بيئية\n• مؤشرات كمية للبصمة البيئية\n• خطة إزالة كربون بغايات (SBTi)\n• شهادة ISO 14001 أو EMAS\n• إبلاغ CDP أو GRI أو TCFD أو مماثل',
 '["No evidence that the organisation manages its environmental impact","Evidence that the organisation manages its environmental impact","The organisation sets objectives for its environmental impact","Objectives tied to environmental risks, with planning and follow-up","Environmental objectives with follow-up and demonstrable reduction results in 80% of key indicators","Certified environmental management system (ISO 14001/EMAS), with net-zero targets and public reporting to international standards (GRI, CDP)"]'::jsonb,
 '["لا يوجد دليل على إدارة المؤسسة لأثرها البيئي","دلائل على إدارة المؤسسة لأثرها البيئي","تضع المؤسسة أهدافاً لأثرها في البيئة","أهداف مرتبطة بالمخاطر البيئية مع تخطيط ومتابعة","أهداف بيئية بمتابعة ونتائج خفض مثبتة في 80% من المؤشرات الرئيسية","نظام إدارة بيئي معتمد (ISO 14001/EMAS) بأهداف حياد كربوني وإبلاغ عام وفق المعايير الدولية (GRI، CDP)"]'::jsonb)
on conflict (code) do update set
  block_en = excluded.block_en, block_ar = excluded.block_ar,
  question_en = excluded.question_en, question_ar = excluded.question_ar,
  context_en = excluded.context_en, context_ar = excluded.context_ar,
  evidence_en = excluded.evidence_en, evidence_ar = excluded.evidence_ar,
  levels_en = excluded.levels_en, levels_ar = excluded.levels_ar,
  sort = excluded.sort;
-- VERIFICAR: select criterion_code, count(*) from public.assessment_questions
--            group by 1 order by 1;   → c1..c7 con 10 cada uno (70 en total)
