-- ============================================================================
-- ORBITAL 360 — Migration 07b · SEED Criterios 2-3 (EN/AR) — re-ejecutable
-- C2 · Organisational Culture & Leadership — C3 · Talent
-- ============================================================================
insert into public.assessment_questions
  (code, criterion_code, ref, sort, block_en, block_ar, question_en, question_ar,
   context_en, context_ar, evidence_en, evidence_ar, levels_en, levels_ar)
values
('P 2.1','c2','2.1',1,'Culture and values','الثقافة والقيم',
 'Values of the organisation','قيم المؤسسة',
 'Values are non-negotiable principles that guide behaviour. They define what kind of organisation you want to be, not just what to do each day.',
 'القيم مبادئ غير قابلة للتفاوض توجه السلوك؛ فهي تحدد نوع المؤسسة المنشودة لا مجرد ما يُنجز يومياً.',
 E'• Formal values document approved by management\n• Onboarding manual with the values explained\n• Code of ethics and/or conduct\n• Values communication plan (internal and external)\n• Sustainability or CSR report with values embedded',
 E'• وثيقة قيم رسمية معتمدة من الإدارة\n• دليل استقبال يشرح القيم\n• مدونة أخلاقيات و/أو سلوك\n• خطة اتصال للقيم (داخلية وخارجية)\n• تقرير استدامة أو مسؤولية اجتماعية يتضمن القيم',
 '["No evidence of defined values in the organisation","Values have been identified in the organisation","Values identified with a specific definition","Values defined and aligned with purpose and vision","Values defined and aligned with purpose and vision, periodically reviewed, updated and communicated","Values systematically reviewed in the last strategic cycle, aligned with purpose and vision, expressing responsibility towards the environment, ensuring ethical conduct and communicated to stakeholders"]'::jsonb,
 '["لا يوجد دليل على قيم محددة في المؤسسة","تم تحديد قيم في المؤسسة","قيم محددة مع تعريف واضح","قيم محددة ومتسقة مع الغاية والرؤية","قيم محددة ومتسقة مع الغاية والرؤية تُراجع وتُحدّث وتُبلغ دورياً","قيم رُوجعت منهجياً في آخر دورة استراتيجية، متسقة مع الغاية والرؤية، تعبر عن المسؤولية تجاه البيئة، تضمن السلوك الأخلاقي وتُبلغ لأصحاب المصلحة"]'::jsonb),

('P 2.2','c2','2.2',2,'Culture and values','الثقافة والقيم',
 'Deployment of the values','نشر القيم',
 'Values matter when they translate into everyday behaviours, conduct standards and real decisions within the organisation''s daily processes.',
 'تكتسب القيم أهميتها عندما تُترجم إلى سلوكيات يومية ومعايير سلوك وقرارات فعلية في عمليات المؤسسة اليومية.',
 E'• Behaviour dictionary per value\n• Code of ethics deployed and signed by people\n• Operating procedures that embed the values\n• Communications to partners and suppliers on expected values\n• Performance evaluation system based on competencies and values\n• Formal recognition programme aligned with values',
 E'• قاموس سلوكيات لكل قيمة\n• مدونة أخلاقيات منشورة وموقعة من الأفراد\n• إجراءات تشغيلية تتضمن القيم\n• مراسلات للشركاء والموردين حول القيم المتوقعة\n• نظام تقييم أداء مبني على الجدارات والقيم\n• برنامج تقدير رسمي متسق مع القيم',
 '["No evidence of the impact of values on how the organisation operates","Behaviours associated with the values have been identified","Values translated into conduct standards (code of ethics, internal rules)","Values translated into conduct standards and integrated into the processes affecting the organisation","Values translated into standards, integrated into processes and reaching key stakeholder groups","Leadership competencies exist that are associated with the values, evaluated, and a source of recognition"]'::jsonb,
 '["لا يوجد دليل على أثر القيم في عمل المؤسسة","تم تحديد السلوكيات المرتبطة بالقيم","قيم مترجمة إلى معايير سلوك (مدونة أخلاقيات، قواعد داخلية)","قيم مترجمة إلى معايير سلوك ومدمجة في العمليات المؤثرة في المؤسسة","قيم مترجمة إلى معايير ومدمجة في العمليات وتصل إلى فئات أصحاب المصلحة الرئيسية","توجد جدارات قيادية مرتبطة بالقيم تُقيَّم وتكون مصدراً للتقدير"]'::jsonb),

('P 2.3','c2','2.3',3,'Culture and values','الثقافة والقيم',
 'Promotion of the values (ethics, integrity, social awareness)','تعزيز القيم (الأخلاق والنزاهة والوعي الاجتماعي)',
 'Measures the extent to which values are truly lived and perceived by all stakeholder groups as authentic and consistent over time.',
 'يقيس مدى معايشة القيم فعلياً وإدراك جميع فئات أصحاب المصلحة لها بوصفها أصيلة ومتسقة عبر الزمن.',
 E'• Internal and external surveys on ethical behaviour\n• Ethics (whistleblowing) channel with handled cases\n• Compliance reports\n• Behaviour or culture audits\n• Public report with ethics and integrity indicators',
 E'• استطلاعات داخلية وخارجية حول السلوك الأخلاقي\n• قناة إبلاغ أخلاقية مع حالات مُعالجة\n• تقارير امتثال\n• تدقيقات سلوك أو ثقافة\n• تقرير عام بمؤشرات الأخلاق والنزاهة',
 '["No measurement plan on whether the values convey ethical, integrated, socially aware behaviour","Measurements showing desired conduct in ethics, integrity and social awareness for at least 20% of stakeholder groups","Measurements for at least 40% of stakeholder groups","Measurements for at least 60% of stakeholder groups","Measurements for at least 80% of stakeholder groups","Measurements for 100% of stakeholder groups"]'::jsonb,
 '["لا توجد خطة قياس لمعرفة ما إذا كانت القيم تنقل سلوكاً أخلاقياً متكاملاً وواعياً اجتماعياً","قياسات تُظهر السلوك المنشود في الأخلاق والنزاهة والوعي الاجتماعي لـ 20% على الأقل من فئات أصحاب المصلحة","قياسات لـ 40% على الأقل من فئات أصحاب المصلحة","قياسات لـ 60% على الأقل من فئات أصحاب المصلحة","قياسات لـ 80% على الأقل من فئات أصحاب المصلحة","قياسات لـ 100% من فئات أصحاب المصلحة"]'::jsonb),

('P 2.4','c2','2.4',4,'Values-based leadership','قيادة مبنية على القيم',
 'Role models in the values','قدوات في القيم',
 'Leaders mirror the values. Their daily conduct is what the organisation learns, observes and reproduces automatically without instruction.',
 'القادة مرآة القيم؛ فسلوكهم اليومي هو ما تتعلمه المؤسسة وتلاحظه وتعيد إنتاجه تلقائياً دون تعليمات.',
 E'• Formal definition of the leadership model\n• Leader development programme aligned with the values\n• Leadership model communication plan\n• Periodic model review procedure\n• Internal awards or recognitions for exemplary leaders\n• External sector recognitions (best CEO, leader of the year…)',
 E'• تعريف رسمي لنموذج القيادة\n• برنامج تطوير قادة متسق مع القيم\n• خطة اتصال لنموذج القيادة\n• إجراء مراجعة دورية للنموذج\n• جوائز أو تقديرات داخلية للقادة القدوة\n• تقديرات خارجية قطاعية (أفضل رئيس تنفيذي، قائد العام…)',
 '["No evidence of a defined leadership model","A defined leadership model exists, consistent with the values","Leadership model consistent with values, aligned with the purpose and communicated to stakeholders","Consistent, aligned and communicated leadership model that is periodically reviewed","Leaders are internal role models in the values, demonstrating the associated competencies and earning internal recognition","Leaders are role models in the values, demonstrating the associated competencies and earning external recognition"]'::jsonb,
 '["لا يوجد دليل على نموذج قيادة محدد","يوجد نموذج قيادة محدد متسق مع القيم","نموذج قيادة متسق مع القيم ومتوائم مع الغاية ومبلغ لأصحاب المصلحة","نموذج قيادة متسق ومتوائم ومبلغ يُراجع دورياً","القادة قدوات داخلية في القيم يظهرون الجدارات المرتبطة بها وينالون تقديرات داخلية","القادة قدوات في القيم يظهرون الجدارات المرتبطة بها وينالون تقديرات خارجية"]'::jsonb),

('P 2.5','c2','2.5',5,'Leadership that drives change','قيادة تدفع التغيير',
 'Change management','إدارة التغيير',
 'In a changing environment, the ability to adapt and transform distinguishes resilient organisations from fragile ones facing market challenges.',
 'في بيئة متغيرة، القدرة على التكيف والتحول هي ما يميز المؤسسات المرنة عن الهشة أمام تحديات السوق.',
 E'• Change risks and opportunities map\n• Formal change-management procedure\n• Strategic transformation plan with horizons\n• Change committees with the people affected\n• Scorecard with success indicators for change projects',
 E'• خريطة مخاطر وفرص التغيير\n• إجراء رسمي لإدارة التغيير\n• خطة تحول استراتيجية بآفاق زمنية\n• لجان تغيير بمشاركة المتأثرين\n• لوحة مؤشرات نجاح مشاريع التغيير',
 '["No evidence of change-management mechanisms in the organisation","Mechanisms exist that identify risks and opportunities fostering change management","Mechanisms identifying risks/opportunities, integrated into the culture, analysing capabilities to face change","Systematised mechanisms identifying risks/opportunities, integrated into the culture, analysing short- and long-term capabilities (strategic projects/challenges)","Systematised mechanisms that involve the people affected and are reviewed to adapt and improve","Systematised mechanisms that measure the success of change projects/challenges"]'::jsonb,
 '["لا يوجد دليل على آليات لإدارة التغيير في المؤسسة","توجد آليات تحدد المخاطر والفرص وتعزز إدارة التغيير","آليات تحدد المخاطر/الفرص ومدمجة في الثقافة وتحلل القدرات لمواجهة التغيير","آليات ممنهجة تحدد المخاطر/الفرص ومدمجة في الثقافة وتحلل القدرات قصيرة وطويلة المدى (مشاريع/تحديات استراتيجية)","آليات ممنهجة تشرك الأشخاص المعنيين وتُراجع للتكيف والتحسين","آليات ممنهجة تقيس نجاح مشاريع/تحديات التغيير"]'::jsonb),

('P 2.6','c2','2.6',6,'Leadership that drives learning','قيادة تعزز التعلم',
 'People''s learning','تعلم الأفراد',
 'An organisation that does not learn repeats mistakes. A learning culture captures experiences and turns them into systematic, sustained improvement.',
 'المؤسسة التي لا تتعلم تكرر الأخطاء؛ فثقافة التعلم تلتقط التجارب وتحولها إلى تحسين منهجي مستدام.',
 E'• Lessons-learned repository after projects\n• Cross-department learning sessions (after action reviews)\n• Membership of excellence clubs, sector associations\n• Talks at sector conferences\n• External awards for good practices (EFQM, ISO, sector)',
 E'• مستودع دروس مستفادة بعد المشاريع\n• جلسات تعلم بين الإدارات (مراجعات ما بعد التنفيذ)\n• عضوية نوادي التميز والجمعيات القطاعية\n• محاضرات في مؤتمرات القطاع\n• جوائز خارجية للممارسات الجيدة (EFQM، ISO، قطاعية)',
 '["No evidence of mechanisms fostering a learning culture","The organisation has mechanisms to identify and learn from improvement and change experiences","Systematic, interdisciplinary mechanisms to identify and learn from experiences","Systematic, interdisciplinary mechanisms; participates in learning and collaboration networks to detect success stories","Systematic mechanisms; participates in networks to detect and present success stories","The organisation has a system of internal good practices and is externally recognised for good practices contributing to the improvement of its environment and/or sector"]'::jsonb,
 '["لا يوجد دليل على آليات تعزز ثقافة التعلم","لدى المؤسسة آليات لتحديد تجارب التحسين والتغيير والتعلم منها","آليات منهجية متعددة التخصصات لتحديد التجارب والتعلم منها","آليات منهجية متعددة التخصصات وتشارك في شبكات تعلم وتعاون لرصد قصص النجاح","آليات منهجية وتشارك في شبكات لرصد قصص النجاح وعرضها","لدى المؤسسة منهجية للممارسات الجيدة الداخلية وهي معترف بها خارجياً بممارسات تسهم في تحسين البيئة و/أو القطاع"]'::jsonb),

('P 2.7','c2','2.7',7,'Leadership that fosters creativity and innovation','قيادة تعزز الإبداع والابتكار',
 'Culture that fosters creativity and innovation','ثقافة تعزز الإبداع والابتكار',
 'Innovation needs space, time and permission. Culture can enable it or smother it even with good financial and human resources available.',
 'يحتاج الابتكار إلى مساحة ووقت وإذن؛ فالثقافة قد تمكّنه أو تخنقه حتى مع توفر موارد مالية وبشرية جيدة.',
 E'• Ideas box with a documented selection process\n• Creativity and innovation training programme\n• Innovation management system (UNE 166002 or similar)\n• Annual innovation plan with goals and indicators\n• Innovation projects implemented with measurable results',
 E'• صندوق أفكار مع عملية اختيار موثقة\n• برنامج تدريب على الإبداع والابتكار\n• نظام إدارة ابتكار (UNE 166002 أو مماثل)\n• خطة ابتكار سنوية بأهداف ومؤشرات\n• مشاريع ابتكار منفذة بنتائج قابلة للقياس',
 '["No evidence of a culture promoting creativity and innovation","Spaces exist where ideas and improvement proposals can be put forward","Spaces for proposing ideas + development of competencies to carry them out","Innovation process stimulating creativity and innovation with systematic spaces for generating and selecting ideas, competency development and project methodologies","Innovation process with plans, goals and objectives, providing time and space to develop projects","Innovation process with plans, goals and objectives, successfully implemented"]'::jsonb,
 '["لا يوجد دليل على ثقافة تعزز الإبداع والابتكار","توجد مساحات لطرح الأفكار ومقترحات التحسين","مساحات لطرح الأفكار + تنمية جدارات لتنفيذها","عملية ابتكار تحفز الإبداع والابتكار بمساحات منهجية لتوليد الأفكار واختيارها وتنمية الجدارات ومنهجيات المشاريع","عملية ابتكار بخطط وغايات وأهداف توفر الوقت والمساحة لتطوير المشاريع","عملية ابتكار بخطط وغايات وأهداف مطبقة بنجاح"]'::jsonb),

('P 2.8','c2','2.8',8,'Leadership that fosters creativity and innovation','قيادة تعزز الإبداع والابتكار',
 'Innovative culture','ثقافة ابتكارية',
 'Measures whether innovation is a one-off project or part of the DNA, perceived as such by all key stakeholder groups in the ecosystem.',
 'يقيس ما إذا كان الابتكار مشروعاً عابراً أم جزءاً من الحمض النووي للمؤسسة كما تدركه فئات أصحاب المصلحة الرئيسية في المنظومة.',
 E'• Innovative-culture surveys per area\n• Innovation indicators (% of employees proposing, ideas/person/year)\n• Scorecard of innovation''s business impact\n• External recognitions in innovation\n• Participation in innovation networks and observatories',
 E'• استطلاعات ثقافة الابتكار حسب المجال\n• مؤشرات ابتكار (% المقترحين، أفكار/شخص/سنة)\n• لوحة قياس أثر الابتكار في الأعمال\n• تقديرات خارجية في الابتكار\n• مشاركة في شبكات ومراصد الابتكار',
 '["No evidence of an innovation culture","Evidence exists that the organisation has an innovation culture","Innovation culture in at least 50% of the organisation with positive perception","Innovation culture systematically measured with positive perception among stakeholders","Innovation culture systematically measured with positive perception above 80% and projects with measurable business impact","Innovation culture is an external benchmark in the sector: shared practices, sector recognitions and participation in innovation networks/observatories"]'::jsonb,
 '["لا يوجد دليل على ثقافة ابتكار","يوجد دليل على امتلاك المؤسسة ثقافة ابتكار","ثقافة ابتكار في 50% على الأقل من المؤسسة بإدراك إيجابي","ثقافة ابتكار تُقاس منهجياً بإدراك إيجابي لدى أصحاب المصلحة","ثقافة ابتكار تُقاس منهجياً بإدراك إيجابي يتجاوز 80% ومشاريع بأثر قابل للقياس في الأعمال","ثقافة ابتكار مرجعية خارجياً في القطاع: ممارسات مشتركة وتقديرات قطاعية ومشاركة في شبكات/مراصد الابتكار"]'::jsonb),

('P 2.9','c2','2.9',9,'Leadership that fosters unity and commitment','قيادة تعزز الوحدة والالتزام',
 'Operational control and decision-making','الضبط التشغيلي واتخاذ القرار',
 'Data-driven decisions require systematic, scheduled control. Without measurement, decisions are intuitions rather than true professional management.',
 'تتطلب القرارات المبنية على البيانات ضبطاً منهجياً مجدولاً؛ فبدون قياس تكون القرارات حدساً لا إدارة مهنية حقيقية.',
 E'• Scorecard with a defined update frequency\n• Operational-control deployment plan\n• Dashboards and business-intelligence tools\n• Committee minutes showing data used to decide\n• Report linking decisions and strategic results',
 E'• لوحة مؤشرات بتواتر تحديث محدد\n• خطة نشر الضبط التشغيلي\n• لوحات معلومات وأدوات ذكاء أعمال\n• محاضر لجان تُظهر استخدام البيانات للقرار\n• تقرير يربط القرارات بالنتائج الاستراتيجية',
 '["No evidence that indicator control is scheduled","The organisation has an operational-control process","Clear, scheduled operational-control process across 50% of the planned deployment","Clear, scheduled operational-control process across 100% of the planned deployment","Operational control at 100% with predictive analytics and real-time dashboards for decision-making","Operational control integrated into the decision-making system, systematically reviewed, with demonstrated impact on strategic results in the last 2 years"]'::jsonb,
 '["لا يوجد دليل على أن ضبط المؤشرات مجدول زمنياً","لدى المؤسسة عملية ضبط تشغيلي","عملية ضبط تشغيلي واضحة ومجدولة في 50% من النشر المخطط","عملية ضبط تشغيلي واضحة ومجدولة في 100% من النشر المخطط","ضبط تشغيلي بنسبة 100% مع تحليلات تنبؤية ولوحات معلومات آنية لاتخاذ القرار","ضبط تشغيلي مدمج في نظام اتخاذ القرار يُراجع منهجياً بأثر مثبت في النتائج الاستراتيجية خلال آخر سنتين"]'::jsonb),

('P 2.10','c2','2.10',10,'Leadership that fosters unity and commitment','قيادة تعزز الوحدة والالتزام',
 'Recognition of achievements','تقدير الإنجازات',
 'Recognising achievements reinforces desired behaviours and tells the ecosystem what the organisation truly values and celebrates as milestones.',
 'تقدير الإنجازات يعزز السلوكيات المنشودة ويخبر المنظومة بما تقدّره المؤسسة وتحتفي به فعلاً كمحطات مهمة.',
 E'• Formal recognition procedure\n• Recognition perception surveys\n• Internal and external communications of achievements\n• Public or internal recognition events\n• Report with communicated success stories',
 E'• إجراء تقدير رسمي\n• استطلاعات إدراك التقدير\n• اتصالات داخلية وخارجية بالإنجازات\n• فعاليات تقدير عامة أو داخلية\n• تقرير بقصص نجاح تم إيصالها',
 '["No measurement plan to recognise people''s successes/achievements","Measurements showing that people''s achievements are recognised","Achievements recognised, shared and positively perceived by 20% of stakeholder groups","Achievements positively perceived by 40% of stakeholder groups","Achievements positively perceived by 60% of stakeholder groups","Achievements positively perceived by 80% of stakeholder groups"]'::jsonb,
 '["لا توجد خطة قياس لتقدير نجاحات/إنجازات الأفراد","قياسات تُظهر أن إنجازات الأفراد تُقدَّر","إنجازات مُقدَّرة ومشتركة ومُدرَكة إيجابياً لدى 20% من فئات أصحاب المصلحة","إنجازات مُدرَكة إيجابياً لدى 40% من فئات أصحاب المصلحة","إنجازات مُدرَكة إيجابياً لدى 60% من فئات أصحاب المصلحة","إنجازات مُدرَكة إيجابياً لدى 80% من فئات أصحاب المصلحة"]'::jsonb),

-- ============================ C3 · TALENT ============================
('P 3.1','c3','3.1',1,'Environment and wellbeing','البيئة والرفاه',
 'Work environment (wellbeing and safety)','بيئة العمل (الرفاه والسلامة)',
 'The physical and emotional environment shapes performance, health and talent attraction. It is the basis of people''s real commitment.',
 'تحدد البيئة المادية والعاطفية الأداء والصحة وجذب المواهب؛ وهي أساس الالتزام الحقيقي للأفراد.',
 E'• Up-to-date psychosocial risk assessment\n• Climate and wellbeing surveys with disaggregated results\n• Workplace wellbeing plan with actions and owners\n• Absenteeism, accident and satisfaction indicators\n• External certifications (GPTW, B Corp, EFR, ISO 45003)',
 E'• تقييم محدث للمخاطر النفسية-الاجتماعية\n• استطلاعات مناخ ورفاه بنتائج مفصلة\n• خطة رفاه وظيفي بإجراءات ومسؤولين\n• مؤشرات الغياب والحوادث والرضا\n• شهادات خارجية (GPTW، B Corp، EFR، ISO 45003)',
 '["No evidence of a wellbeing-oriented work environment","Desired, safe environment fostering wellbeing, positively perceived by at least 50% of people","Desired, safe environment perceived by at least 75% of people","Desired, safe environment perceived by 100% of people","Environment with active continuous-improvement wellbeing plans, indicators measured systematically and positive results sustained over the last 2 years","Sector benchmark in workplace wellbeing, with external certifications (Great Place to Work, B Corp, EFR or similar) and benchmarking with other organisations"]'::jsonb,
 '["لا يوجد دليل على بيئة عمل موجهة للرفاه","بيئة منشودة وآمنة تعزز الرفاه يدركها إيجابياً 50% على الأقل من الأفراد","بيئة منشودة وآمنة يدركها 75% على الأقل من الأفراد","بيئة منشودة وآمنة يدركها 100% من الأفراد","بيئة بخطط تحسين مستمر للرفاه ومؤشرات تُقاس منهجياً ونتائج إيجابية مستدامة خلال آخر سنتين","مرجعية قطاعية في الرفاه الوظيفي بشهادات خارجية (Great Place to Work، B Corp، EFR أو مماثلة) ومقارنات مع مؤسسات أخرى"]'::jsonb),

('P 3.2','c3','3.2',2,'Empowerment and capabilities','التمكين والقدرات',
 'Empowerment of people','تمكين الأفراد',
 'When people have capabilities, tools and autonomy, they decide better and faster. Empowerment unleashes the whole team''s productive potential.',
 'عندما يمتلك الأفراد القدرات والأدوات والاستقلالية، يقررون أفضل وأسرع؛ فالتمكين يطلق الإمكانات الإنتاجية للفريق بأكمله.',
 E'• Job descriptions and capability maps\n• Documented empowerment plan\n• Internal communities of practice\n• Delegation and autonomous decision-making indicators\n• Results of projects led by self-organised teams',
 E'• توصيفات وظائف وخرائط قدرات\n• خطة تمكين موثقة\n• مجتمعات ممارسة داخلية\n• مؤشرات التفويض واتخاذ القرار المستقل\n• نتائج مشاريع قادتها فرق ذاتية التنظيم',
 '["No plans identifying people''s functional activities","Plans exist identifying people''s functional activities","Plans identifying activities and capabilities and securing the tools to develop them","Plans identifying activities, capabilities, tools, and at least 75% of people communicate and share their learning","Plans covering 100% of people; the organisation measures empowerment''s impact on project results and satisfaction","Empowerment fully embedded in the culture: people take on responsibilities and decide autonomously, with demonstrable impact on strategic results"]'::jsonb,
 '["لا توجد خطط تحدد الأنشطة الوظيفية للأفراد","توجد خطط تحدد الأنشطة الوظيفية للأفراد","خطط تحدد الأنشطة والقدرات وتؤمّن أدوات تطويرها","خطط تحدد الأنشطة والقدرات والأدوات ويشارك 75% على الأقل من الأفراد تعلمهم","خطط تغطي 100% من الأفراد وتقيس المؤسسة أثر التمكين في نتائج المشاريع والرضا","تمكين مدمج كلياً في الثقافة: يتحمل الأفراد المسؤوليات ويقررون باستقلالية بأثر مثبت في النتائج الاستراتيجية"]'::jsonb),

('P 3.3','c3','3.3',3,'Creativity and innovation','الإبداع والابتكار',
 'Creativity and innovation','الإبداع والابتكار',
 'Innovation is born from those closest to the problem. Fostering people''s creativity builds a sustainable, differentiating competitive advantage in the sector.',
 'يولد الابتكار من الأقرب إلى المشكلة؛ وتعزيز إبداع الأفراد يبني ميزة تنافسية مستدامة ومميزة في القطاع.',
 E'• Innovation project management procedure\n• Impact indicators (% success, return, ideas implemented)\n• Perception surveys after each project\n• Annual innovation report\n• External recognitions or resulting new business lines',
 E'• إجراء إدارة مشاريع الابتكار\n• مؤشرات أثر (% النجاح، العائد، الأفكار المنفذة)\n• استطلاعات إدراك بعد كل مشروع\n• تقرير ابتكار سنوي\n• تقديرات خارجية أو خطوط أعمال جديدة ناتجة',
 '["No evidence of projects fostering creativity, innovation and disruptive thinking","Structured projects exist that foster creativity, innovation and disruptive thinking","Structured projects; impact is measured and positively perceived in 50% of projects","Structured projects; impact is measured and positively perceived in 75% of projects","Structured projects; impact measured and positively perceived in 100% of projects, with measurable results in implemented innovation","Benchmark in creativity and innovation: people lead disruptive projects that are externally recognised or have generated new business lines"]'::jsonb,
 '["لا يوجد دليل على مشاريع تعزز الإبداع والابتكار والتفكير التحويلي","توجد مشاريع منظمة تعزز الإبداع والابتكار والتفكير التحويلي","مشاريع منظمة يُقاس أثرها ويُدرك إيجابياً في 50% من المشاريع","مشاريع منظمة يُقاس أثرها ويُدرك إيجابياً في 75% من المشاريع","مشاريع منظمة يُقاس أثرها ويُدرك إيجابياً في 100% من المشاريع مع نتائج قابلة للقياس في الابتكار المنفذ","مرجعية في الإبداع والابتكار: الأفراد يقودون مشاريع تحويلية معترفاً بها خارجياً أو ولّدت خطوط أعمال جديدة"]'::jsonb),

('P 3.4','c3','3.4',4,'Learning','التعلم',
 'People''s learning','تعلم الأفراد',
 'Continuous training keeps people competitive and the organisation adaptable. It is strategic investment, not an expense to cut in hard times.',
 'يحافظ التدريب المستمر على تنافسية الأفراد وقابلية المؤسسة للتكيف؛ فهو استثمار استراتيجي لا نفقة تُقتطع في الأوقات الصعبة.',
 E'• Annual training plan with budget\n• Systematic training-needs detection\n• Indicators of training''s impact on performance\n• Kirkpatrick evaluations (reaction, learning, behaviour, results)\n• Formalised corporate university or internal school\n• Awards or mentions for talent management',
 E'• خطة تدريب سنوية بميزانية\n• رصد منهجي للاحتياجات التدريبية\n• مؤشرات أثر التدريب في الأداء\n• تقييمات كيركباتريك (التفاعل، التعلم، السلوك، النتائج)\n• جامعة مؤسسية أو مدرسة داخلية رسمية\n• جوائز أو إشادات بإدارة المواهب',
 '["No evidence of training actions for people","Sporadic training actions for people","Indicators and training plans supporting change management and performance improvement for at least 50% of the people involved in the processes","Indicators and training plans for at least 75% of the people involved in the processes","Training plans for 100% of people with performance-impact indicators and results measured systematically","Corporate university or own school and external recognition as a benchmark in training and talent development"]'::jsonb,
 '["لا يوجد دليل على إجراءات تدريب للأفراد","إجراءات تدريب متفرقة للأفراد","مؤشرات وخطط تدريب تدعم إدارة التغيير وتحسين الأداء لـ 50% على الأقل من الأفراد المعنيين بالعمليات","مؤشرات وخطط تدريب لـ 75% على الأقل من الأفراد المعنيين بالعمليات","خطط تدريب لـ 100% من الأفراد بمؤشرات أثر في الأداء ونتائج تُقاس منهجياً","جامعة مؤسسية أو مدرسة خاصة واعتراف خارجي كمرجعية في التدريب وتنمية المواهب"]'::jsonb),

('P 3.5','c3','3.5',5,'Management by objectives','الإدارة بالأهداف',
 'Management by objectives for people','الإدارة بالأهداف للأفراد',
 'Clear individual objectives connect daily effort with strategy and make each person''s contribution to the common result measurable.',
 'الأهداف الفردية الواضحة تربط الجهد اليومي بالاستراتيجية وتجعل مساهمة كل فرد في النتيجة المشتركة قابلة للقياس.',
 E'• Management-by-objectives procedure (MBO/OKR)\n• Individual objective-setting templates\n• Documented performance-review sessions\n• Scorecard with % achievement per person/area\n• Perception surveys on the MBO system',
 E'• إجراء إدارة بالأهداف (MBO/OKR)\n• نماذج تحديد أهداف فردية\n• جلسات تقييم أداء موثقة\n• لوحة مؤشرات بنسبة الإنجاز لكل شخص/مجال\n• استطلاعات إدراك حول نظام الإدارة بالأهداف',
 '["No evidence of management-by-objectives policies for people","Management-by-objectives policies for some people","Policies positively perceived by 50% of people and objectives achieved in 25% of cases in the last 2 years","Policies positively perceived by 75% and objectives achieved in 50% of cases in the last 2 years","Policies positively perceived by 100% and objectives achieved in 70% of cases in the last 2 years","Policies fully deployed, positively perceived by 100% and objectives achieved in more than 85% of cases, with continuous review"]'::jsonb,
 '["لا يوجد دليل على سياسات إدارة بالأهداف للأفراد","سياسات إدارة بالأهداف لبعض الأفراد","سياسات يدركها إيجابياً 50% من الأفراد وتتحقق الأهداف في 25% من الحالات خلال آخر سنتين","سياسات يدركها إيجابياً 75% وتتحقق الأهداف في 50% من الحالات خلال آخر سنتين","سياسات يدركها إيجابياً 100% وتتحقق الأهداف في 70% من الحالات خلال آخر سنتين","سياسات منشورة كلياً يدركها إيجابياً 100% وتتحقق الأهداف في أكثر من 85% من الحالات مع مراجعة مستمرة"]'::jsonb),

('P 3.6','c3','3.6',6,'Motivation and commitment','التحفيز والالتزام',
 'Motivation in projects','التحفيز في المشاريع',
 'A motivated team delivers better, retains customers and attracts talent. Motivation is visible from outside and spreads quickly to other teams.',
 'الفريق المحفز ينجز أفضل ويحتفظ بالعملاء ويجذب المواهب؛ والتحفيز مرئي من الخارج وينتقل سريعاً إلى فرق أخرى.',
 E'• Engagement / motivation surveys\n• Disaggregated voluntary-turnover indicators\n• 1:1 sessions with motivation follow-up\n• Project-specific motivation programmes\n• Key-talent retention rate',
 E'• استطلاعات انخراط / تحفيز\n• مؤشرات دوران طوعي مفصلة\n• جلسات فردية بمتابعة التحفيز\n• برامج تحفيز خاصة بالمشاريع\n• معدل الاحتفاظ بالمواهب الرئيسية',
 '["No evidence of motivation in projects","Evidence of people motivated in projects","At least 40% of people show motivation, positively perceived by their stakeholders","At least 60% of people show motivation","At least 80% of people show motivation","100% of people show motivation, perceived by all stakeholder groups, translating into low voluntary turnover"]'::jsonb,
 '["لا يوجد دليل على التحفيز في المشاريع","دلائل على أفراد محفزين في المشاريع","40% على الأقل من الأفراد محفزون بإدراك إيجابي لدى أصحاب مصلحتهم","60% على الأقل من الأفراد محفزون","80% على الأقل من الأفراد محفزون","100% من الأفراد محفزون بإدراك جميع فئات أصحاب المصلحة، ما ينعكس في انخفاض الدوران الطوعي"]'::jsonb),

('P 3.7','c3','3.7',7,'Balance and work-life','التوازن والتوفيق',
 'Work-life balance','التوازن بين العمل والحياة',
 'Work-life balance is a key factor of health, productivity and talent retention in any demanding sector today.',
 'التوازن بين العمل والحياة عامل رئيسي للصحة والإنتاجية والاحتفاظ بالمواهب في أي قطاع متطلب اليوم.',
 E'• Documented work-life balance policy\n• Concrete measures (flexible hours, remote work, leave)\n• Balance perception surveys\n• EFR (family-responsible company) certification or similar\n• Cases published as sector good practices',
 E'• سياسة توازن موثقة\n• تدابير ملموسة (ساعات مرنة، عمل عن بُعد، إجازات)\n• استطلاعات إدراك التوازن\n• شهادة EFR (شركة مسؤولة أسرياً) أو مماثلة\n• حالات منشورة كممارسات جيدة قطاعية',
 '["No evidence of a plan ensuring work-life balance","A plan exists ensuring work-life balance","The organisation is flexible in supporting balance, positively perceived by 40% of people","Balance positively perceived by 80% of people","Balance positively perceived by 100% of people","Benchmark in work-life balance: specific certifications (EFR, B Corp or similar) and cited as good practice by other organisations in the sector"]'::jsonb,
 '["لا يوجد دليل على خطة تضمن التوازن بين العمل والحياة","توجد خطة تضمن التوازن بين العمل والحياة","المؤسسة مرنة في دعم التوفيق ويدركه إيجابياً 40% من الأفراد","توازن يدركه إيجابياً 80% من الأفراد","توازن يدركه إيجابياً 100% من الأفراد","مرجعية في التوازن: شهادات خاصة (EFR، B Corp أو مماثلة) وتُذكر كممارسة جيدة لدى مؤسسات القطاع"]'::jsonb),

('P 3.8','c3','3.8',8,'Talent recognition','تقدير المواهب',
 'Reward, recognition and care','المكافأة والتقدير والرعاية',
 'Talent is cared for or it leaves. Recognising, retaining and motivating prevents the loss of critical knowledge and reduces turnover and hiring costs.',
 'المواهب تُرعى وإلا رحلت؛ فالتقدير والاحتفاظ والتحفيز يمنع فقدان المعرفة الحرجة ويخفض تكاليف الدوران والتوظيف.',
 E'• Recognition programme (monetary and non-monetary)\n• Pay policy with sector benchmarking\n• Recognition surveys (do you feel valued?)\n• Turnover indicators vs the sector\n• Number of spontaneous applications / referrals',
 E'• برنامج تقدير (مادي وغير مادي)\n• سياسة أجور بمقارنة قطاعية\n• استطلاعات تقدير (هل تشعرون بالتقدير؟)\n• مؤشرات دوران مقارنة بالقطاع\n• عدد الطلبات التلقائية / الترشيحات',
 '["No defined plan to recognise, retain and/or motivate talent","A defined plan exists to recognise, retain and/or motivate talent","Talent recognition and retention measurements positively perceived by 50% of people","Recognition and retention perceived by 75% of people","Recognition and retention perceived by 100% of people","Benchmark in talent management and retention: turnover below the sector and spontaneous attraction of candidates"]'::jsonb,
 '["لا توجد خطة محددة لتقدير المواهب والاحتفاظ بها و/أو تحفيزها","توجد خطة محددة لتقدير المواهب والاحتفاظ بها و/أو تحفيزها","قياسات تقدير واحتفاظ بالمواهب يدركها إيجابياً 50% من الأفراد","تقدير واحتفاظ يدركهما 75% من الأفراد","تقدير واحتفاظ يدركهما 100% من الأفراد","مرجعية في إدارة المواهب والاحتفاظ بها: دوران أدنى من القطاع وجذب تلقائي للمرشحين"]'::jsonb),

('P 3.9','c3','3.9',9,'Internal communication','الاتصال الداخلي',
 'Internal communication and transparency','الاتصال والشفافية الداخلية',
 'Clear, transparent communication aligns people, prevents rumours and builds trust in management and in the shared project.',
 'الاتصال الواضح والشفاف يوائم الأفراد ويمنع الشائعات ويبني الثقة في الإدارة وفي المشروع المشترك.',
 E'• Annual internal communication plan\n• Active channels (intranet, newsletter, town halls)\n• Communication perception surveys\n• Active-listening committees or people councils\n• Cases where team opinions changed decisions',
 E'• خطة اتصال داخلي سنوية\n• قنوات نشطة (إنترانت، نشرة، لقاءات عامة)\n• استطلاعات إدراك الاتصال\n• لجان إصغاء فعّال أو مجالس أفراد\n• حالات غيّرت فيها آراء الفريق القرارات',
 '["No plans for clear, transparent communication","Management plans exist evidencing clear, transparent communication","Communication plans positively perceived by 50% of people","Communication plans positively perceived by 75% of people","Communication plans positively perceived by 100% of people","Two-way, systematic internal communication: management is periodically accountable and people perceive their opinions impact decisions"]'::jsonb,
 '["لا توجد خطط لاتصال واضح وشفاف","توجد خطط إدارية تُثبت اتصالاً واضحاً وشفافاً","خطط اتصال يدركها إيجابياً 50% من الأفراد","خطط اتصال يدركها إيجابياً 75% من الأفراد","خطط اتصال يدركها إيجابياً 100% من الأفراد","اتصال داخلي ثنائي الاتجاه ومنهجي: تحاسب الإدارة دورياً ويدرك الأفراد أن آراءهم تؤثر في القرارات"]'::jsonb),

('P 3.10','c3','3.10',10,'Diversity and equality','التنوع والمساواة',
 'Diversity and equal opportunity','التنوع وتكافؤ الفرص',
 'Diversity enriches decision-making, reflects social reality and is a growing legal and reputational requirement in today''s market context.',
 'يثري التنوع اتخاذ القرار ويعكس الواقع الاجتماعي وهو مطلب قانوني وسمعي متنامٍ في سياق السوق الحالي.',
 E'• Registered, current equality plan\n• Parity indicators by level and category\n• Pay audit with the wage gap\n• Inclusion perception surveys\n• Certifications (equality marks, Bequal, EDGE) and adherence to sector initiatives',
 E'• خطة مساواة مسجلة وسارية\n• مؤشرات تكافؤ حسب المستوى والفئة\n• تدقيق أجور مع فجوة الأجر\n• استطلاعات إدراك الشمول\n• شهادات (علامات مساواة، Bequal، EDGE) والانضمام إلى مبادرات قطاعية',
 '["No gender diversity and/or equal-opportunity plan","Plan defining gender diversity and/or equal opportunity in the last strategic cycle, without defined measurements","Parity in gender diversity and equal opportunity, positively perceived by 50% of people","Parity positively perceived by 75% of people","Parity positively perceived by 100% of people","Benchmark in diversity, equity and inclusion: external certifications and active participation in sector equality initiatives"]'::jsonb,
 '["لا توجد خطة للتنوع الجندري و/أو تكافؤ الفرص","خطة تحدد التنوع الجندري و/أو تكافؤ الفرص في آخر دورة استراتيجية دون قياسات محددة","تكافؤ في التنوع الجندري وتكافؤ الفرص يدركه إيجابياً 50% من الأفراد","تكافؤ يدركه إيجابياً 75% من الأفراد","تكافؤ يدركه إيجابياً 100% من الأفراد","مرجعية في التنوع والإنصاف والشمول: شهادات خارجية ومشاركة نشطة في مبادرات المساواة القطاعية"]'::jsonb)
on conflict (code) do update set
  block_en = excluded.block_en, block_ar = excluded.block_ar,
  question_en = excluded.question_en, question_ar = excluded.question_ar,
  context_en = excluded.context_en, context_ar = excluded.context_ar,
  evidence_en = excluded.evidence_en, evidence_ar = excluded.evidence_ar,
  levels_en = excluded.levels_en, levels_ar = excluded.levels_ar,
  sort = excluded.sort;
-- VERIFICAR: select count(*) from assessment_questions;  → 30 (C1+C2+C3)
